openapi: 3.0.3
info:
  title: calendar
  description: Calendar docs here
  version: "1.0"
paths:
  /calendar:
    get:
      operationId: getCalendarEvents
      summary: List calendar events
      description: Get a list of a user's calendar events for the month in ?date
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/monthDate
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /calendar/discover:
    get:
      operationId: discoverCalendarEvents
      summary: Discover calendar events
      description: |-
        Get a list of calendar events
        Initially, call without a `nextCursor` parameter
        For every successive call, use the `nextCursor` property returned in the previous call & the `number` of entries desired for this call
        The `nextCursor` internally keeps track of the `offset` of the results, the initial request parameters, and accounts for discrepancies that might arise from time elapsed between calls
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/calendarDiscoveryScope
        - $ref: ../parameters.yaml#/calendarDiscoveryCategories
        - $ref: ../parameters.yaml#/calendarDiscoveryTags
        - $ref: ../parameters.yaml#/calendarDiscoveryFeatured
        - $ref: ../parameters.yaml#/calendarDiscoveryNonFeatured
        - $ref: ../parameters.yaml#/calendarDiscoveryPersonalized
        - $ref: ../parameters.yaml#/calendarDiscoveryMinimumInterestCount
        - $ref: ../parameters.yaml#/calendarDiscoveryMinimumRemainingMinutes
        - $ref: ../parameters.yaml#/calendarDiscoveryUpcomingOffsetMinutes
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/calendarDiscoveryNextCursor
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventDiscoveryResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /calendar/featured:
    get:
      operationId: getFeaturedCalendarEvents
      summary: List featured calendar events
      description: Get a list of a featured calendar events for the month in ?date
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/monthDate
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /calendar/following:
    get:
      operationId: getFollowedCalendarEvents
      summary: List followed calendar events
      description: Get a list of a followed calendar events for the month in ?date
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/monthDate
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /calendar/search:
    get:
      operationId: searchCalendarEvents
      summary: Search for calendar events
      description: Get a list of calendar events by search terms
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/calendarSearchTerm
        - $ref: ../parameters.yaml#/utcOffset
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/calendar/{groupId}":
    get:
      operationId: getGroupCalendarEvents
      summary: List a group's calendar events
      description: Get a list of a group's calendar events
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/groupId
        - $ref: ../parameters.yaml#/monthDate
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/calendar/{groupId}/event":
    parameters:
      - $ref: ../parameters.yaml#/groupId
    post:
      operationId: createGroupCalendarEvent
      summary: Create a calendar event
      description: Creates an event for a group on the calendar
      tags:
        - calendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/CreateCalendarEventRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/calendar/{groupId}/{calendarId}":
    delete:
      operationId: deleteGroupCalendarEvent
      summary: Delete a calendar event
      description: Delete a group calendar event
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/groupId
        - $ref: ../parameters.yaml#/calendarId
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/DeleteCalendarEventSuccess.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    get:
      operationId: getGroupCalendarEvent
      summary: Get a calendar event
      description: Get a group calendar event
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/groupId
        - $ref: ../parameters.yaml#/calendarId
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/calendar/{groupId}/{calendarId}.ics":
    get:
      operationId: getGroupCalendarEventICS
      summary: Download calendar event as ICS
      description: Returns the specified calendar in iCalendar (ICS) format.
      tags:
        - calendar
      parameters:
        - $ref: ../parameters.yaml#/groupId
        - $ref: ../parameters.yaml#/calendarId
      responses:
        "200":
          $ref: ../responses/calendar/ICSResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "404":
          $ref: ../responses/calendar/ICSNotFoundError.yaml
  "/calendar/{groupId}/{calendarId}/event":
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/calendarId
    put:
      operationId: updateGroupCalendarEvent
      summary: Update a calendar event
      description: Updates an event for a group on the calendar
      tags:
        - calendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateCalendarEventRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/calendar/{groupId}/{calendarId}/follow":
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/calendarId
    post:
      operationId: followGroupCalendarEvent
      summary: Follow a calendar event
      description: Follow or unfollow an event on a group's calendar
      tags:
        - calendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/FollowCalendarEventRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/calendar/CalendarEventResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
tags:
  $ref: ../tags.yaml
