openapi: 3.0.3
info:
  title: economy
  version: '1.0'
  description: Economy Docs Here
paths:
  /Steam/transactions:
    get:
      summary: List Steam Transactions
      operationId: getSteamTransactions
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/TransactionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get all own Steam transactions.
  '/Steam/transactions/{transactionId}':
    parameters:
      - $ref: ../parameters.yaml#/transactionId
    get:
      summary: Get Steam Transaction
      operationId: getSteamTransaction
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/TransactionResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Get a single Steam transactions by ID. This returns the exact same information as `getSteamTransactions`, so no point in using this endpoint.'
      deprecated: true
  /Admin/transactions:
    get:
      summary: Get Admin Transactions
      operationId: getAdminTransactions
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/TransactionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get all own Admin transactions.
      x-internal: true
  '/Admin/transactions/{transactionId}':
    parameters:
      - $ref: ../parameters.yaml#/transactionId
    get:
      summary: Get Admin Transactions
      operationId: getAdminTransaction
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/TransactionResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Get a single Admin transactions by ID. This returns the exact same information as `getAdminTransactions`, so no point in using this endpoint.'
      deprecated: true
      x-internal: true
  /auth/user/subscription:
    get:
      summary: Get Current Subscriptions
      operationId: getCurrentSubscriptions
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/UserSubscriptionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get a list of all current user subscriptions.
  /user/subscription/recent:
    get:
      summary: Get Recent Subscription
      operationId: getRecentSubscription
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/UserSubscriptionResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get the most recent user subscription.
  /user/bulk/gift/purchases:
    parameters:
      - $ref: ../parameters.yaml#/mostRecentFlag
    get:
      summary: Get Bulk Gift Purchases
      operationId: getBulkGiftPurchases
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/BulkPurchasesListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get bulk gift purchases made by the user.
  '/users/{userId}/subscription/eligible':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/steamId
    get:
      summary: Get User Subscription Eligiblity
      operationId: getUserSubscriptionEligible
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/UserSubscriptionEligibleResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get the user's eligibility status for subscriptions.
  '/users/{userId}/credits/eligible':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/subscriptionId
    get:
      summary: Get User Credits Eligiblity
      operationId: getUserCreditsEligible
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/UserCreditsEligibleResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get the user's eligibility status for subscriptions based on available credits.
  /subscriptions:
    get:
      summary: List Subscriptions
      operationId: getSubscriptions
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/SubscriptionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'List all existing Subscriptions. For example, "vrchatplus-monthly" and "vrchatplus-yearly".'
  '/licenseGroups/{licenseGroupId}':
    parameters:
      - $ref: ../parameters.yaml#/licenseGroupId
    get:
      summary: Get License Group
      operationId: getLicenseGroup
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/LicenseGroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get a single License Group by given ID.
  '/listing/{productId}':
    parameters:
      - $ref: ../parameters.yaml#/productId
      - $ref: ../parameters.yaml#/hydrate
    get:
      summary: Get Product Listing
      operationId: getProductListing
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/ProductListingResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets a product listing'
  '/user/{userId}/listings':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
      - $ref: ../parameters.yaml#/hydrate
      - $ref: ../parameters.yaml#/groupIdFilter
      - $ref: ../parameters.yaml#/active
    get:
      summary: Get User Product Listings
      operationId: getProductListings
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/ProductListingListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Gets the product listings of a given user
  '/tokenBundles':
    get:
      summary: List Token Bundles
      operationId: getTokenBundles
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/TokenBundleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the list of token bundles'
  '/tilia/status':
    get:
      summary: Get Tilia Status
      operationId: getTiliaStatus
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/TiliaStatusResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the status of Tilia integration'
  '/user/{userId}/tilia/tos':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Tilia TOS Agreement Status
      operationId: getTiliaTos
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/TiliaTOSResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the status of the agreement of a user to the Tilia TOS'
    put:
      summary: Update Tilia TOS Agreement Status
      operationId: updateTiliaTos
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/UpdateTiliaTOSResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateTiliaTOSRequest.yaml
      description: 'Updates the status of the agreement of a user to the Tilia TOS'
  '/user/{userId}/balance':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Balance
      operationId: getBalance
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/BalanceResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the balance of a user'
  '/user/{userId}/balance/earnings':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Balance Earnings
      operationId: getBalanceEarnings
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/BalanceResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the balance of a user from earnings'
  '/user/{userId}/economy/account':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Economy Account
      operationId: getEconomyAccount
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/EconomyAccountResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the economy account of a user'
  '/economy/licenses/active':
    get:
      summary: Get Active Licenses
      operationId: getActiveLicenses
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/LicenseListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets active licenses'
  '/economy/store':
    parameters:
      - $ref: ../parameters.yaml#/storeId
      - $ref: ../parameters.yaml#/hydrateListings
      - $ref: ../parameters.yaml#/hydrateProducts
    get:
      summary: Get Store
      operationId: getStore
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/StoreResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Gets a store
  '/economy/store/shelves':
    parameters:
      - $ref: ../parameters.yaml#/storeId
      - $ref: ../parameters.yaml#/hydrateListings
      - $ref: ../parameters.yaml#/storeView
    get:
      summary: Get Store Shelves
      operationId: getStoreShelves
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/economy/StoreShelfListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Gets the shelves for a store
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
