openapi: 3.0.3
info:
  title: economy
  description: Economy Docs Here
  version: "1.0"
paths:
  /Admin/transactions:
    get:
      operationId: getAdminTransactions
      summary: Get Admin Transactions
      description: Get all own Admin transactions.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/TransactionListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
      x-internal: true
  "/Admin/transactions/{transactionId}":
    parameters:
      - $ref: ../parameters.yaml#/transactionId
    get:
      operationId: getAdminTransaction
      deprecated: true
      summary: Get Admin Transactions
      description: "Get a single Admin transactions by ID. This returns the exact same information as `getAdminTransactions`, so no point in using this endpoint."
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/TransactionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
      x-internal: true
  /Steam/transactions:
    get:
      operationId: getSteamTransactions
      summary: List Steam Transactions
      description: Get all own Steam transactions.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/TransactionListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/Steam/transactions/{transactionId}":
    parameters:
      - $ref: ../parameters.yaml#/transactionId
    get:
      operationId: getSteamTransaction
      deprecated: true
      summary: Get Steam Transaction
      description: "Get a single Steam transactions by ID. This returns the exact same information as `getSteamTransactions`, so no point in using this endpoint."
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/TransactionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /auth/user/subscription:
    get:
      operationId: getCurrentSubscriptions
      summary: Get Current Subscriptions
      description: Get a list of all current user subscriptions.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/UserSubscriptionListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /economy/licenses/active:
    get:
      operationId: getActiveLicenses
      summary: Get Active Licenses
      description: Gets active licenses
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/LicenseListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /economy/purchase/listing:
    post:
      operationId: purchaseProductListing
      summary: Purchase Product Listing
      description: Purchases a product listing
      tags:
        - economy
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/PurchaseProductListingRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/ProductPurchaseResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /economy/purchases:
    parameters:
      - $ref: ../parameters.yaml#/buyerId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
      - $ref: ../parameters.yaml#/mostRecentFlag
      - $ref: ../parameters.yaml#/sortProductPurchase
      - $ref: ../parameters.yaml#/orderShort
    get:
      operationId: getProductPurchases
      summary: Get Product Purchases
      description: Gets product purchases
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/ProductPurchaseListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /economy/store:
    parameters:
      - $ref: ../parameters.yaml#/storeId
      - $ref: ../parameters.yaml#/hydrateListings
      - $ref: ../parameters.yaml#/hydrateProducts
    get:
      operationId: getStore
      summary: Get Store
      description: Gets a store
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/StoreResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /economy/store/shelves:
    parameters:
      - $ref: ../parameters.yaml#/storeId
      - $ref: ../parameters.yaml#/hydrateListings
      - $ref: ../parameters.yaml#/storeView
    get:
      operationId: getStoreShelves
      summary: Get Store Shelves
      description: Gets the shelves for a store
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/StoreShelfListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/licenseGroups/{licenseGroupId}":
    parameters:
      - $ref: ../parameters.yaml#/licenseGroupId
    get:
      operationId: getLicenseGroup
      summary: Get License Group
      description: Get a single License Group by given ID.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/LicenseGroupResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/listing/{productId}":
    parameters:
      - $ref: ../parameters.yaml#/productId
      - $ref: ../parameters.yaml#/hydrate
    get:
      operationId: getProductListing
      summary: Get Product Listing
      description: Gets a product listing
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/ProductListingResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/products/{productId}":
    parameters:
      - $ref: ../parameters.yaml#/productId
    get:
      operationId: getProductListingAlternate
      deprecated: true
      summary: Get Product Listing (alternate)
      description: Gets a product listing
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/ProductListingResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /subscriptions:
    get:
      operationId: getSubscriptions
      summary: List Subscriptions
      description: 'List all existing Subscriptions. For example, "vrchatplus-monthly" and "vrchatplus-yearly".'
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/SubscriptionListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /tilia/status:
    get:
      operationId: getTiliaStatus
      summary: Get Tilia Status
      description: Gets the status of Tilia integration
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/TiliaStatusResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /tokenBundles:
    get:
      operationId: getTokenBundles
      summary: List Token Bundles
      description: Gets the list of token bundles
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/TokenBundleListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /user/bulk/gift/purchases:
    parameters:
      - $ref: ../parameters.yaml#/mostRecentFlag
    get:
      operationId: getBulkGiftPurchases
      summary: Get Bulk Gift Purchases
      description: Get bulk gift purchases made by the user.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/BulkPurchasesListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /user/subscription/recent:
    get:
      operationId: getRecentSubscription
      summary: Get Recent Subscription
      description: Get the most recent user subscription.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/UserSubscriptionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/user/{userId}/balance":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getBalance
      summary: Get Balance
      description: Gets the balance of a user
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/BalanceResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/user/{userId}/balance/earnings":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getBalanceEarnings
      summary: Get Balance Earnings
      description: Gets the balance of a user from earnings
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/BalanceResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/user/{userId}/economy/account":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getEconomyAccount
      summary: Get Economy Account
      description: Gets the economy account of a user
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/EconomyAccountResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/user/{userId}/listings":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
      - $ref: ../parameters.yaml#/hydrate
      - $ref: ../parameters.yaml#/groupIdFilter
      - $ref: ../parameters.yaml#/active
    get:
      operationId: getProductListings
      summary: Get User Product Listings
      description: Gets the product listings of a given user
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/ProductListingListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/user/{userId}/tilia/tos":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getTiliaTos
      summary: Get Tilia TOS Agreement Status
      description: Gets the status of the agreement of a user to the Tilia TOS
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/TiliaTOSResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    put:
      operationId: updateTiliaTos
      summary: Update Tilia TOS Agreement Status
      description: Updates the status of the agreement of a user to the Tilia TOS
      tags:
        - economy
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateTiliaTOSRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/UpdateTiliaTOSResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/credits/eligible":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/subscriptionId
    get:
      operationId: getUserCreditsEligible
      summary: Get User Credits Eligiblity
      description: Get the user's eligibility status for subscriptions based on available credits.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/UserCreditsEligibleResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/subscription/eligible":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/steamId
    get:
      operationId: getUserSubscriptionEligible
      summary: Get User Subscription Eligiblity
      description: Get the user's eligibility status for subscriptions.
      tags:
        - economy
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/economy/UserSubscriptionEligibleResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
tags:
  $ref: ../tags.yaml
