openapi: 3.0.3
info:
  title: economy
  version: '1.0'
  description: Economy Docs Here
paths:
  /Steam/transactions:
    get:
      summary: List Steam Transactions
      operationId: getSteamTransactions
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1Steam~1transactions/get"
      responses:
        '200':
          $ref: ../responses/economy/TransactionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get all own Steam transactions.
  '/Steam/transactions/{transactionId}':
    parameters:
      - $ref: ../parameters.yaml#/transactionId
    get:
      summary: Get Steam Transaction
      operationId: getSteamTransaction
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1Steam~1transactions~1{transactionId}/get"
      responses:
        '200':
          $ref: ../responses/economy/TransactionResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Get a single Steam transactions by ID. This returns the exact same information as `getSteamTransactions`, so no point in using this endpoint.'
      deprecated: true
  /Admin/transactions:
    get:
      summary: Get Admin Transactions
      operationId: getAdminTransactions
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1Admin~1transactions/get"
      responses:
        '200':
          $ref: ../responses/economy/TransactionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get all own Admin transactions.
      x-internal: true
  '/Admin/transactions/{transactionId}':
    parameters:
      - $ref: ../parameters.yaml#/transactionId
    get:
      summary: Get Admin Transactions
      operationId: getAdminTransaction
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1Admin~1transactions~1{transactionId}/get"
      responses:
        '200':
          $ref: ../responses/economy/TransactionResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Get a single Admin transactions by ID. This returns the exact same information as `getAdminTransactions`, so no point in using this endpoint.'
      deprecated: true
      x-internal: true
  /auth/user/subscription:
    get:
      summary: Get Current Subscriptions
      operationId: getCurrentSubscriptions
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1auth~1user~1subscription/get"
      responses:
        '200':
          $ref: ../responses/economy/UserSubscriptionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get a list of all current user subscriptions.
  /subscriptions:
    get:
      summary: List Subscriptions
      operationId: getSubscriptions
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1subscriptions/get"
      responses:
        '200':
          $ref: ../responses/economy/SubscriptionListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'List all existing Subscriptions. For example, "vrchatplus-monthly" and "vrchatplus-yearly".'
  '/licenseGroups/{licenseGroupId}':
    parameters:
      - $ref: ../parameters.yaml#/licenseGroupId
    get:
      summary: Get License Group
      operationId: getLicenseGroup
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1licenseGroups~1{licenseGroupId}/get"
      responses:
        '200':
          $ref: ../responses/economy/LicenseGroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Get a single License Group by given ID.
  '/listing/{productId}':
    parameters:
      - $ref: ../parameters.yaml#/productId
      - $ref: ../parameters.yaml#/hydrate
    get:
      summary: Get Product Listing
      operationId: getProductListing
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1listing~1{productId}/get"
      responses:
        '200':
          $ref: ../responses/economy/ProductListingResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets a product listing'
  '/user/{userId}/listings':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
      - $ref: ../parameters.yaml#/hydrate
      - $ref: ../parameters.yaml#/groupIdFilter
      - $ref: ../parameters.yaml#/active
    get:
      summary: Get User Product Listings
      operationId: getProductListings
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1user~1{userId}~1listings/get"
      responses:
        '200':
          $ref: ../responses/economy/ProductListingListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: Gets the product listings of a given user
  '/tokenBundles':
    get:
      summary: List Token Bundles
      operationId: getTokenBundles
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1tokenBundles/get"
      responses:
        '200':
          $ref: ../responses/economy/TokenBundleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the list of token bundles'
  '/tilia/status':
    get:
      summary: Get Tilia Status
      operationId: getTiliaStatus
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1tilia~1status/get"
      responses:
        '200':
          $ref: ../responses/economy/TiliaStatusResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the status of Tilia integration'
  '/user/{userId}/tilia/tos':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Tilia TOS Agreement Status
      operationId: getTiliaTos
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1user~1{userId}~1tilia~1tos/get"
      responses:
        '200':
          $ref: ../responses/economy/TiliaTOSResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the status of the agreement of a user to the Tilia TOS'
  '/user/{userId}/balance':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Balance
      operationId: getBalance
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/economy.yaml#/~1user~1{userId}~1balance/get"
      responses:
        '200':
          $ref: ../responses/economy/BalanceResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      tags:
        - economy
      description: 'Gets the balance of a user'
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
