openapi: 3.0.3
info:
  title: favorites
  version: '1.0'
  description: Favorites Docs Here
paths:
  /favorites:
    get:
      summary: List Favorites
      tags:
        - favorites
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1favorites/get"
      responses:
        '200':
          $ref: ../responses/favorites/FavoriteListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getFavorites
      security:
        - authCookie: []
      description: Returns a list of favorites.
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
        - schema:
            type: string
          in: query
          name: type
          description: 'The type of favorites to return, FavoriteType.'
        - $ref: ../parameters.yaml#/tag
    post:
      summary: Add Favorite
      operationId: addFavorite
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1favorites/post"
      responses:
        '200':
          $ref: ../responses/favorites/FavoriteResponse.yaml
        '400':
          $ref: ../responses/favorites/FavoriteAddAlreadyFavoritedError.yaml
        '403':
          $ref: ../responses/favorites/FavoriteAddNotFriendsError.yaml
      description: |-
        Add a new favorite.

        Friend groups are named `group_0` through `group_3`. Avatar and World groups are named `avatars1` to `avatars4` and `worlds1` to `worlds4`.

        You cannot add people whom you are not friends with to your friends list. Destroying a friendship removes the person as favorite on both sides.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/AddFavoriteRequest.yaml
            examples:
              Example Favorite Friend:
                value:
                  type: friend
                  favoriteId: usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469
                  tags:
                    - group_0
              Example Favorite Avatar:
                value:
                  type: avatar
                  favoriteId: avtr_912d66a4-4714-43b8-8407-7de2cafbf55b
                  tags:
                    - avatars1
        description: ''
      tags:
        - favorites
  '/favorites/{favoriteId}':
    parameters:
      - $ref: ../parameters.yaml#/favoriteId
    delete:
      summary: Remove Favorite
      operationId: removeFavorite
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1favorites~1{favoriteId}/delete"
      responses:
        '200':
          $ref: ../responses/favorites/FavoriteRemovedSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/favorites/FavoriteNotFoundError.yaml
      description: Remove a favorite from your favorites list.
      tags:
        - favorites
  /favorite/groups:
    get:
      summary: List Favorite Groups
      tags:
        - favorites
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1favorite~1groups/get"
      responses:
        '200':
          $ref: ../responses/favorites/FavoriteGroupListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getFavoriteGroups
      security:
        - authCookie: []
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
        - schema:
            type: string
          in: query
          name: ownerId
          description: The owner of whoms favorite groups to return. Must be a UserID.
      description: Return a list of favorite groups owned by a user. Returns the same information as `getFavoriteGroups`.
  '/favorite/group/{favoriteGroupType}/{favoriteGroupName}/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/favoriteGroupType
      - $ref: ../parameters.yaml#/favoriteGroupName
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Show Favorite Group
      tags:
        - favorites
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1favorite~1group~1{favoriteGroupType}~1{favoriteGroupName}~1{userId}/get"
      responses:
        '200':
          $ref: ../responses/favorites/FavoriteGroupResponse.yaml
      operationId: getFavoriteGroup
      security:
        - authCookie: []
      description: Fetch information about a specific favorite group.
    put:
      summary: Update Favorite Group
      operationId: updateFavoriteGroup
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1favorite~1group~1{favoriteGroupType}~1{favoriteGroupName}~1{userId}/put"
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateFavoriteGroupRequest.yaml
      tags:
        - favorites
      description: Update information about a specific favorite group.
    delete:
      summary: Clear Favorite Group
      operationId: clearFavoriteGroup
      security:
        - authCookie: []
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1favorite~1group~1{favoriteGroupType}~1{favoriteGroupName}~1{userId}/delete"
      responses:
        '200':
          $ref: ../responses/favorites/FavoriteGroupClearedSuccess.yaml
      tags:
        - favorites
      description: Clear ALL contents of a specific favorite group.
  '/auth/user/favoritelimits':
    parameters: []
    get:
      summary: Get Favorite Limits
      tags:
        - favorites
      x-codeSamples:
        $ref: "../codeSamples/favorites.yaml#/~1auth~1user~1favoritelimits/get"
      responses:
        '200':
          $ref: ../responses/favorites/FavoriteLimitsResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getFavoriteLimits
      security:
        - authCookie: []
      description: Return information about a specific Favorite.
      parameters: []
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml