openapi: 3.0.3
info:
  title: favorites
  description: Favorites Docs Here
  version: "1.0"
paths:
  /auth/user/favoritelimits:
    parameters: []
    get:
      operationId: getFavoriteLimits
      summary: Get Favorite Limits
      description: Return information about a specific Favorite.
      tags:
        - favorites
      parameters: []
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/favorites/FavoriteLimitsResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/favorite/group/{favoriteGroupType}/{favoriteGroupName}/{userId}":
    parameters:
      - $ref: ../parameters.yaml#/favoriteGroupType
      - $ref: ../parameters.yaml#/favoriteGroupName
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getFavoriteGroup
      summary: Show Favorite Group
      description: Fetch information about a specific favorite group.
      tags:
        - favorites
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/favorites/FavoriteGroupResponse.yaml
    put:
      operationId: updateFavoriteGroup
      summary: Update Favorite Group
      description: Update information about a specific favorite group.
      tags:
        - favorites
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateFavoriteGroupRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          description: OK
    delete:
      description: Clear ALL contents of a specific favorite group.
      summary: Clear Favorite Group
      operationId: clearFavoriteGroup
      tags:
        - favorites
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/favorites/FavoriteGroupClearedSuccess.yaml
  /favorite/groups:
    get:
      operationId: getFavoriteGroups
      summary: List Favorite Groups
      description: Return a list of favorite groups owned by a user. Returns the same information as `getFavoriteGroups`.
      tags:
        - favorites
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/userIdAdmin
        - name: ownerId
          description: The owner of whoms favorite groups to return. Must be a UserID.
          in: query
          schema:
            type: string
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/favorites/FavoriteGroupListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /favorites:
    get:
      operationId: getFavorites
      summary: List Favorites
      description: Returns a list of favorites.
      tags:
        - favorites
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
        - name: type
          description: "The type of favorites to return, FavoriteType."
          in: query
          schema:
            type: string
        - $ref: ../parameters.yaml#/tag
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/favorites/FavoriteListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    post:
      operationId: addFavorite
      summary: Add Favorite
      description: |-
        Add a new favorite.

        Friend groups are named `group_0` through `group_3`. Avatar and World groups are named `avatars1` to `avatars4` and `worlds1` to `worlds4`.

        You cannot add people whom you are not friends with to your friends list. Destroying a friendship removes the person as favorite on both sides.
      tags:
        - favorites
      requestBody:
        description: ""
        content:
          application/json:
            examples:
              Example Favorite Avatar:
                value:
                  type: avatar
                  favoriteId: avtr_912d66a4-4714-43b8-8407-7de2cafbf55b
                  tags:
                    - avatars1
              Example Favorite Friend:
                value:
                  type: friend
                  favoriteId: usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469
                  tags:
                    - group_0
            schema:
              $ref: ../requests/AddFavoriteRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/favorites/FavoriteResponse.yaml
        "400":
          $ref: ../responses/favorites/FavoriteAddAlreadyFavoritedError.yaml
        "403":
          $ref: ../responses/favorites/FavoriteAddNotFriendsError.yaml
  "/favorites/{favoriteId}":
    parameters:
      - $ref: ../parameters.yaml#/favoriteId
    delete:
      operationId: removeFavorite
      summary: Remove Favorite
      description: Remove a favorite from your favorites list.
      tags:
        - favorites
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/favorites/FavoriteRemovedSuccess.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "404":
          $ref: ../responses/favorites/FavoriteNotFoundError.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
tags:
  $ref: ../tags.yaml
