openapi: 3.0.3
info:
  title: groups
  version: '1.0'
  description: Groups
paths:
  /groups:
    post:
      summary: Create Group
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Creates a Group and returns a Group object
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupRequest.yaml
  '/groups/{groupId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group by ID
      tags:
        - groups
      operationId: getGroup
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
  responses: {}
