openapi: 3.0.3
info:
  title: groups
  version: '1.0'
  description: Group Docs Here
paths:
  /groups:
    post:
      summary: Create Group
      description: Creates a Group and returns a Group object. **Requires VRC+ Subscription.**
      operationId: createGroup
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group by ID
      description: Returns a single Group by ID.
      tags:
        - groups
      operationId: getGroup
      parameters:
        - in: query
          name: includeRoles
          schema:
            type: boolean
          required: false
          description: Include roles for the Group object. Defaults to false.
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    put:
      summary: Update Group
      description: Updates a Group and returns it.
      operationId: updateGroup
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateGroupRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Delete Group
      operationId: deleteGroup
      tags:
        - groups
      description: Deletes a Group.
      responses:
        '200':
          $ref: ../responses/groups/DeleteGroupSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/announcement':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Announcement
      description: |-
        Returns the announcement for a Group.
        If no announcement has been made, then it returns **empty object**. 
        If an announcement exists, then it will always return all fields except `imageId` and `imageUrl` which may be null.
      operationId: getGroupAnnouncements
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupAnnouncementResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    post:
      summary: Create Group Announcement
      description: Creates an Announcement for a Group.
      operationId: createGroupAnnouncement
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupAnnouncementRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupAnnouncementResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Delete Group Announcement
      description: Deletes the announcement for a Group.
      operationId: deleteGroupAnnouncement
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/DeleteGroupAnnouncementSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/auditLogs':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Audit Logs
      description: Returns a list of audit logs for a Group.
      operationId: getGroupAuditLogs
      tags:
        - groups
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      responses:
        # '200':
        #   $ref: ../responses/groups/GroupAuditLogsResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/invites':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Invites Sent
      description: Returns a list of members that have been invited to the Group.
      operationId: getGroupInvites
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    post:
      summary: Invite User to Group
      description: Sends an invite to a user to join the group.
      operationId: createGroupInvite
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupInviteRequest.yaml
      responses:
        '200':
          description: OK
        '400':
          description: User <displayName> is already invited
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/invites/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/userId
    delete:
      summary: Delete User Invite
      description: Deletes an Group invite sent to a User
      operationId: deleteGroupInvite
      tags:
        - groups
      responses:
        '200':
          description: OK
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/join':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    post:
      summary: Join Group
      description: Join a Group by ID and returns the joined Group.
      operationId: joinGroup
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '400':
          $ref: ../responses/groups/GroupAlreadyMemberError.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/leave':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    post:
      summary: Leave Group
      description: Leave a group by ID.
      operationId: leaveGroup
      tags:
        - groups
      responses:
        '200':
          description: OK
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/members':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: List Group Members
      description: Returns a List of all Group Members
      operationId: getGroupMembers
      tags:
        - groups
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
        '400':
          $ref: ../responses/users/UsersInvalidSearchError.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/members/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Group Member
      description: Returns a LimitedGroup Member.
      operationId: getGroupMember
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupLimitedMemberResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    put:
      summary: Update Group Member
      description: Updates a Group Member
      operationId: updateGroupMember
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateGroupMemberRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupLimitedMemberResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/members/{userId}/roles/{groupRoleId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/groupRoleId
    put:
      summary: Add Role to GroupMember
      description: Adds a Role to a Group Member
      operationId: addGroupMemberRole
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleIDListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Remove Role from GroupMember
      description: Removes a Role from a Group Member
      operationId: removeGroupMemberRole
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleIDListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/requests':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Join Requests
      description: Returns a list of members that have requested to join the Group.
      operationId: getGroupRequests
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Cancel Group Join Request
      description: Cancels a request sent to join the group.
      operationId: cancelGroupRequest
      tags:
        - groups
      responses:
        '200':
          description: OK
        '400':
          description: You can't cancel a join request if you didn't request to join․
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/requests/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/userId
    put:
      summary: Respond Group Join request
      description: Responds to a Group Join Request with Accept/Deny
      operationId: respondGroupJoinRequest
      tags:
        - groups
      responses:
        '200':
          description: OK
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/RespondGroupJoinRequest.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/roles':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Roles
      description: Returns a Group Role by ID.
      operationId: getGroupRoles
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    post:
      summary: Create GroupRole
      description: Create a Group role.
      operationId: createGroupRole
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupRoleRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/roles/{groupRoleId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/groupRoleId
    put:
      summary: Update Group Role
      description: Updates a group role by ID.
      operationId: updateGroupRole
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateGroupRoleRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Delete Group Role
      description: Deletes a Group Role by ID and returns the remaining roles.
      operationId: deleteGroupRole
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotMemberError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
  responses: {}
