openapi: 3.0.3
info:
  title: groups
  version: '1.0'
  description: Groups
paths:
  /groups:
    post:
      summary: Create Group
      security:
        - apiKeyCookie: []
          authCookie: []
      description: |-
        Creates a Group and returns a Group object
        **Requires VRC+ Subscription.**
      tags:
        - groups
      operationId: createGroup
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupRequest.yaml
  '/groups/{groupId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group by ID
      description: Gets a Group by ID and returns a Group object
      tags:
        - groups
      operationId: getGroup
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    put:
      summary: Update Group
      tags:
        - groups
      operationId: updateGroup
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      description: Updates a Group
      security:
        - apiKeyCookie: []
          authCookie: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateGroupRequest.yaml
    delete:
      summary: Delete Group
      tags:
        - groups
      operationId: deleteGroup
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Deletes a group
      responses:
        '200':
          description: OK
  '/groups/{groupId}/roles':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Roles
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
      operationId: getGroupRoles
      description: Gets a Group Role by ID
    post:
      summary: Create GroupRole
      operationId: createGroupRole
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleResponse.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupRoleRequest.yaml
      description: Create a Group role
  '/groups/{groupId}/join':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    post:
      summary: Join Group
      operationId: groupJoin
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
      description: Joins a Group by ID and returns a joined Group object.
  '/groups/{groupId}/leave':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    post:
      summary: Leaves a Group
      operationId: groupLeave
      tags:
        - groups
      responses:
        '200':
          description: OK
      description: Leaves a group by ID.
  '/groups/{groupId}/requests':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      description: Gets List of Members that have requested to join Group
      summary: Get Requests to Group
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
      operationId: getGroupRequests
    delete:
      summary: Deletes outbound Group Request
      operationId: deleteGroupRequest
      tags:
        - groups
      responses:
        '200':
          description: OK
      description: Deletes a Group Request sent to the requested group.
  '/groups/{groupId}/invites':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      description: Gets list of Members that have been invited into a Group.
      summary: Get Invites from Group
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
      operationId: getGroupInvites
    post:
      description: Sends invite to a Group
      summary: Invite User to Group
      tags:
        - groups
      responses:
        '200':
          description: OK
        '400':
          description: User {display-name} is already invited
      operationId: createGroupInvite
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupInviteRequest.yaml
  '/groups/{groupId}/invites/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/userId
    delete:
      description: Univites a User from a Group
      summary: Delete User Invite
      tags:
        - groups
      responses:
        '200': 
          description: OK
      operationId: deleteGroupInvite
  '/groups/{groupId}/roles/{groupRoleId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/groupRoleId
    put:
      summary: Update Group Role
      operationId: updateGroupRole
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateGroupRoleRequest.yaml
      description: Updates a group role by ID
    delete:
      description: Deletes a Group Role by ID and returns the remaining roles.
      summary: Delete Group Role
      tags:
        - groups
      operationId: deleteGroupRole
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
  responses: {}
