openapi: 3.0.3
info:
  title: groups
  version: '1.0'
  description: Group Docs Here
paths:
  /groups:
    post:
      summary: Create Group
      description: Creates a Group and returns a Group object. **Requires VRC+ Subscription.**
      operationId: createGroup
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group by ID
      description: Returns a single Group by ID.
      tags:
        - groups
      operationId: getGroup
      parameters:
        - in: query
          name: includeRoles
          schema:
            type: boolean
          required: false
          description: Include roles for the Group object. Defaults to false.
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    put:
      summary: Update Group
      description: Updates a Group and returns it.
      operationId: updateGroup
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateGroupRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Delete Group
      operationId: deleteGroup
      tags:
        - groups
      description: Deletes a Group.
      responses:
        '200':
          $ref: ../responses/groups/DeleteGroupSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/roles':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Roles
      description: Returns a Group Role by ID.
      operationId: getGroupRoles
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    post:
      summary: Create GroupRole
      description: Create a Group role.
      operationId: createGroupRole
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupRoleRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/members':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Members
      description: Returns a List of all Group Members
      operationId: getGroupMembers
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/join':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    post:
      summary: Join Group
      description: Join a Group by ID and returns the joined Group.
      operationId: joinGroup
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/leave':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    post:
      summary: Leave Group
      description: Leave a group by ID.
      operationId: leaveGroup
      tags:
        - groups
      responses:
        '200':
          description: OK
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/requests':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Join Requests
      description: Returns a list of members that have requested to join the Group.
      operationId: getGroupRequests
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Cancel Group Join Request
      description: Cancels a request sent to join the group.
      operationId: cancelGroupRequest
      tags:
        - groups
      responses:
        '200':
          description: OK
        '400':
          description: You can't cancel a join request if you didn't request to join․
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/invites':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group Invites Sent
      description: Returns a list of members that have been invited to the Group.
      operationId: getGroupInvites
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupMemberListResponse.yaml
        '403':
          $ref: ../responses/groups/GroupNotMemberError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    post:
      summary: Invite User to Group
      description: Sends an invite to a user to join the group.
      operationId: createGroupInvite
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateGroupInviteRequest.yaml
      responses:
        '200':
          description: OK
        '400':
          description: User <displayName> is already invited
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/invites/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/userId
    delete:
      summary: Delete User Invite
      description: Deletes an Group invite sent to a User
      operationId: deleteGroupInvite
      tags:
        - groups
      responses:
        '200':
          description: OK
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
  '/groups/{groupId}/roles/{groupRoleId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
      - $ref: ../parameters.yaml#/groupRoleId
    put:
      summary: Update Group Role
      description: Updates a group role by ID.
      operationId: updateGroupRole
      tags:
        - groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateGroupRoleRequest.yaml
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
    delete:
      summary: Delete Group Role
      description: Deletes a Group Role by ID and returns the remaining roles.
      operationId: deleteGroupRole
      tags:
        - groups
      responses:
        '200':
          $ref: ../responses/groups/GroupRoleListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/groups/GroupNotMemberError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
  responses: {}
