openapi: 3.0.3
info:
  title: groups
  version: '1.0'
  description: Groups
paths:
  '/groups/{groupId}':
    parameters:
      - $ref: ../parameters.yaml#/groupId
    get:
      summary: Get Group by ID
      tags:
        - groups
      operationId: getGroup
      responses:
        '200':
          $ref: ../responses/worlds/GroupResponse.yaml
        '404':
          $ref: ../responses/worlds/GroupNotFoundError.yaml
      security:
        - apiKeyCookie: []
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
