openapi: 3.0.3
info:
  title: instances
  version: '1.0'
  description: Instances Docs Here
paths:
  '/instances/{worldId}:{instanceId}':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    get:
      summary: Get Instance
      tags:
        - instances
      operationId: getInstance
      security:
        - apiKeyCookie: []
          authCookie: []
      description: |-
        Returns an instance. Please read [Instances Tutorial](https://vrchatapi.github.io/tutorials/instances/) for more information on Instances.

        If an invalid instanceId is provided, this endpoint will simply return "null"!
      responses:
        '200':
          $ref: ../responses/instances/InstanceResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
  '/instances/{worldId}:{instanceId}/shortName':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    get:
      summary: Get Instance Short Name
      tags:
        - instances
      operationId: getShortName
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Returns an instance short name.
      responses:
        '200':
          $ref: ../responses/instances/InstanceShortNameResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
  '/instances/{worldId}:{instanceId}/invite':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    post:
      summary: Send Self Invite
      tags:
        - instances
      operationId: sendSelfInvite
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Sends an invite to the instance to yourself.
      responses:
        '200':
          $ref: ../responses/instances/InstanceSelfInviteSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
