openapi: 3.0.3
info:
  title: inventory
  description: "The inventory manages collectable items, such as drop bundles and their contents."
  version: "1.0"
paths:
  /inventory:
    parameters:
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
      - $ref: ../parameters.yaml#/inventoryHolderId
      - $ref: ../parameters.yaml#/inventoryEquipSlot
      - $ref: ../parameters.yaml#/inventorySortOrder
      - $ref: ../parameters.yaml#/inventoryItemTags
      - $ref: ../parameters.yaml#/inventoryItemTypes
      - $ref: ../parameters.yaml#/inventoryItemFlags
      - $ref: ../parameters.yaml#/inventoryItemNotTypes
      - $ref: ../parameters.yaml#/inventoryItemNotFlags
      - $ref: ../parameters.yaml#/inventoryItemArchived
    get:
      operationId: getInventory
      summary: Get Inventory
      description: Returns an Inventory object.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/NoPermission.yaml
  /inventory/cloning/direct:
    parameters:
      - $ref: ../parameters.yaml#/inventoryPedestalItemId
      - $ref: ../parameters.yaml#/inventoryPedestalDuration
    post:
      operationId: shareInventoryItemDirect
      summary: Share Inventory Item Direct
      description: Share content directly with other users.
      tags:
        - inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/ShareInventoryItemDirectRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryShareResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /inventory/cloning/pedestal:
    parameters:
      - $ref: ../parameters.yaml#/inventoryPedestalItemId
      - $ref: ../parameters.yaml#/inventoryPedestalDuration
    get:
      operationId: shareInventoryItemPedestal
      summary: Share Inventory Item by Pedestal
      description: Returns an InventorySpawn object.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventorySpawnResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /inventory/collections:
    get:
      operationId: getInventoryCollections
      summary: List Inventory Collections
      description: Returns a list of collection names.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryCollectionsResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /inventory/drops:
    parameters:
      - $ref: ../parameters.yaml#/active
    get:
      operationId: getInventoryDrops
      summary: List Inventory Drops
      description: Returns a list of InventoryDrop objects.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryDropListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /inventory/spawn:
    parameters:
      - $ref: ../parameters.yaml#/inventorySpawnItemId
    get:
      operationId: spawnInventoryItem
      summary: Spawn Inventory Item
      description: Returns an InventorySpawn object.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventorySpawnResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/inventory/template/{inventoryTemplateId}":
    parameters:
      - $ref: ../parameters.yaml#/inventoryTemplateId
    get:
      operationId: getInventoryTemplate
      summary: Get Inventory Template
      description: Returns an InventoryTemplate object.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryTemplateResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/inventory/{inventoryItemId}":
    parameters:
      - $ref: ../parameters.yaml#/inventoryItemId
    get:
      operationId: getOwnInventoryItem
      summary: Get Own Inventory Item
      description: Returns an InventoryItem object held by the currently logged in user.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryItemResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    put:
      operationId: updateOwnInventoryItem
      summary: Update Own Inventory Item
      description: Returns the modified InventoryItem object as held by the currently logged in user.
      tags:
        - inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateInventoryItemRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryItemResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    delete:
      operationId: deleteOwnInventoryItem
      summary: Delete Own Inventory Item
      description: Deletes an InventoryItem from the inventory of the currently logged in user.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/DeleteInventoryItemResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/inventory/{inventoryItemId}/consume":
    parameters:
      - $ref: ../parameters.yaml#/inventoryItemId
    put:
      operationId: consumeOwnInventoryItem
      summary: Consume Own Inventory Item
      description: Returns the modified InventoryItem object as held by the currently logged in user.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/ConsumeInventoryItemResponse.yaml
        "400":
          $ref: ../responses/inventory/InventoryItemNotConsumable.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/inventory/{inventoryItemId}/equip":
    delete:
      operationId: unequipOwnInventorySlot
      summary: Unequip Own Inventory Slot
      description: Unequips the InventoryItem in the given slot of the inventory of the currently logged in user.
      tags:
        - inventory
      parameters:
        - $ref: ../parameters.yaml#/inventoryItemSlotAsId
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/UnequipInventorySlotResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    put:
      operationId: equipOwnInventoryItem
      summary: Equip Own Inventory Item
      description: Returns the modified InventoryItem object as held by the currently logged in user.
      tags:
        - inventory
      parameters:
        - $ref: ../parameters.yaml#/inventoryItemId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/EquipInventoryItemRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryItemResponse.yaml
        "400":
          $ref: ../responses/inventory/InventoryItemNotEquippable.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/inventory/{inventoryItemId}":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/inventoryItemId
    get:
      operationId: getUserInventoryItem
      summary: Get User Inventory Item
      description: Returns an InventoryItem object held by the given user.
      tags:
        - inventory
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/inventory/InventoryItemResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
tags:
  $ref: ../tags.yaml
