openapi: 3.0.3
info:
  title: invite
  version: '1.0'
  description: A
paths:
  '/message/{userId}/message':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: List Invite Messages
      tags:
        - invite
      responses:
        '200':
          $ref: ../responses/invite/InviteMessageListResponse.yaml
        '400':
          $ref: ../responses/invite/InviteMessageInvalidSlotNumberError.yaml
        '401':
          $ref: ../responses/NotAuthorizedActionError.yaml
      operationId: getInviteMessages
      description: Returns a list of all that users Invite Messages. Admin Credentials are required to view messages of other users!
  '/message/{userId}/message/{messageId}':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/messageId
    get:
      summary: Get Invite Messages
      tags:
        - invite
      responses:
        '200':
          $ref: ../responses/invite/InviteMessageResponse.yaml
        '400':
          $ref: ../responses/invite/InviteMessageInvalidSlotNumberError.yaml
        '401':
          $ref: ../responses/NotAuthorizedActionError.yaml
      operationId: getInviteMessage
      description: Returns a single Invite Message. This returns the exact same information but less than `getInviteMessages`. Admin Credentials are required to view messages of other users!
    put:
      summary: Update Invite Message
      operationId: updateInviteMessage
      description: |-
        Updates a single Invite Message and then returns a list of all of them. Admin Credentials are required to update messages of other users!

        Updating a message automatically sets the cooldown timer to 60 minutes. Trying to edit a message before the cooldown timer expires results in a 429 Too Fast Error.
      responses:
        '200':
          $ref: ../responses/invite/InviteMessageListResponse.yaml
        '400':
          $ref: ../responses/invite/InviteMessageInvalidSlotNumberError.yaml
        '401':
          $ref: ../responses/NotAuthorizedActionError.yaml
        '429':
          $ref: ../responses/invite/InviteMessageUpdateRateLimitError.yaml
      tags:
        - invite
    delete:
      summary: Reset Invite Message
      operationId: resetInviteMessage
      responses:
        '200':
          $ref: ../responses/invite/InviteMessageListResponse.yaml
        '400':
          $ref: ../responses/invite/InviteMessageInvalidSlotNumberError.yaml
        '401':
          $ref: ../responses/NotAuthorizedActionError.yaml
        '429':
          $ref: ../responses/invite/InviteMessageUpdateRateLimitError.yaml
      tags:
        - invite
      description: |-
        Resets a single Invite Message back to it's original message, and then returns a list of all of them. Admin Credentials are required to update messages of other users!

        Resetting a message respects the rate-limit, but resetting it does not set the rate-limit to 60 like when editing it. It is possible to edit it right after resetting it. Trying to edit a message before the cooldown timer expires results in a 429 Too Fast Error.
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
