openapi: 3.0.3
info:
  title: invite
  version: '1.0'
  description: A
paths:
  '/message/{userId}/message':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get Invite Messages
      tags:
        - invite
      responses:
        '200':
          $ref: ../responses/invite/InviteMessageListResponse.yaml
      operationId: getInviteMessages
      description: Returns a list of all that users Invite Messages. Admin Credentials are required to view messages of other users.
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
