openapi: 3.0.3
info:
  title: jams
  description: Jams Docs Here
  version: "1.0"
paths:
  /jams:
    get:
      operationId: getJams
      summary: Show jams list
      description: |-
        Lists World Jams or Avatar Jams, both currently running and ones that have ended.

        `isActive` is used to select only active or already ended jams.

        `type` is used to select only world or avatar jams, and can only take `world` or `avatar`.
        ``
      tags:
        - jams
      parameters:
        - name: type
          description: Only show jams of this type (`avatar` or `world`).
          in: query
          schema:
            type: string
            example: avatar
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/jams/JamListResponse.yaml
  "/jams/{jamId}":
    parameters:
      - $ref: ../parameters.yaml#/jamId
    get:
      operationId: getJam
      summary: Show jam information
      description: Returns a jam.
      tags:
        - jams
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/jams/JamResponse.yaml
        "404":
          $ref: ../responses/jams/JamNotFoundError.yaml
  "/jams/{jamId}/submissions":
    parameters:
      - $ref: ../parameters.yaml#/jamId
    get:
      operationId: getJamSubmissions
      summary: Show jam submissions
      description: Returns all submissions of a jam. Can filter by contentId (for world or avatar jams) or submitterId (for a participant).
      tags:
        - jams
      parameters:
        - $ref: ../parameters.yaml#/contentId
        - $ref: ../parameters.yaml#/submitterId
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/jams/JamSubmissionListResponse.yaml
        "404":
          $ref: ../responses/jams/JamNotFoundError.yaml
    post:
      operationId: submitJamContent
      summary: Submit Jam Content
      description: Submits content to a jam. The content must have been uploaded by the submitter, and both the content upload and jam submission must be made within the jam's designated times.
      tags:
        - jams
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateJamSubmissionRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/jams/JamSubmissionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "404":
          $ref: ../responses/jams/JamNotFoundError.yaml
  "/jams/{jamId}/submissions/{jamSubmissionId}":
    parameters:
      - $ref: ../parameters.yaml#/jamId
      - $ref: ../parameters.yaml#/jamSubmissionId
    delete:
      operationId: deleteJamSubmission
      summary: Delete Jam Submission
      description: Withdraws a content submission from a jam.
      tags:
        - jams
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/jams/DeleteJamSubmissionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/NoPermission.yaml
        "404":
          $ref: ../responses/jams/JamNotFoundError.yaml
