openapi: 3.0.3
info:
  title: message
  version: '1.0'
  description: A
paths:
  '/message/{userId}/message':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Your GET endpoint
      tags:
        - message
      responses: {}
      operationId: getInviteMessages
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
