openapi: 3.0.3
info:
  title: miscellaneous
  description: Miscellaneous endpoints that do not fit into any other category.
  version: "1.0"
paths:
  /auth/permissions:
    parameters: []
    get:
      operationId: getAssignedPermissions
      summary: Get Assigned Permissions
      description: Returns a list of all permissions currently granted by the user. Permissions are assigned e.g. by subscribing to VRC+.
      tags:
        - miscellaneous
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/permissions/PermissionListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /config:
    get:
      operationId: getConfig
      summary: Fetch API Config
      description: |-
        API config contains configuration that the clients needs to work properly.

        Currently the most important value here is `clientApiKey` which is used for all other API endpoints.
      tags:
        - miscellaneous
      security: []
      responses:
        "200":
          $ref: ../responses/system/APIConfigResponse.yaml
  /css/app.css:
    get:
      operationId: getCSS
      summary: Download CSS
      description: Fetches the CSS code to the frontend React website.
      tags:
        - miscellaneous
      parameters:
        - $ref: ../parameters.yaml#/variant
        - $ref: ../parameters.yaml#/branch
      responses:
        "200":
          description: "**Note:** VRChat uses 302 Redirect to Cloudfront. The implementing library **must** support and follow redirects natively."
          content:
            text/css:
              schema:
                type: string
        "400":
          $ref: ../responses/system/DownloadSourceCodeAccessError.yaml
  /health:
    get:
      operationId: getHealth
      deprecated: true
      summary: Check API Health
      description: |-
        ~~Gets the overall health status, the server name, and the current build version tag of the API.~~

        **DEPRECATED:** VRChat has suddenly restricted this endpoint for unknown reasons, and now always return 401 Unauthorized.
      tags:
        - miscellaneous
      security: []
      responses:
        "200":
          $ref: ../responses/system/APIHealthResponse.yaml
  /infoPush:
    get:
      operationId: getInfoPush
      summary: Show Information Notices
      description: |-
        IPS (Info Push System) is a system for VRChat to push out dynamic information to the client. This is primarily used by the Quick-Menu info banners, but can also be used to e.g. alert you to update your game to the latest version.

        `include` is used to query what Information Pushes should be included in the response. If include is missing or empty, then no notices will normally be returned. This is an "any of" search.

        `require` is used to limit what Information Pushes should be included in the response. This is usually used in combination with `include`, and is an "all of" search.
      tags:
        - miscellaneous
      security:
        - authCookie: []
      parameters:
        - $ref: ../parameters.yaml#/require
        - $ref: ../parameters.yaml#/include
      responses:
        "200":
          $ref: ../responses/system/InfoPushListResponse.yaml
      x-badges:
        - color: gold
          label: "Status: Early Access (Still Under Development)"
  /js/app.js:
    get:
      operationId: getJavaScript
      summary: Download JavaScript
      description: Fetches the JavaScript code to the frontend React website.
      tags:
        - miscellaneous
      parameters:
        - $ref: ../parameters.yaml#/variant
        - $ref: ../parameters.yaml#/branch
      responses:
        "200":
          description: "**Note:** VRChat uses 302 Redirect to Cloudfront. The implementing library **must** support and follow redirects natively."
          content:
            application/javascript:
              schema:
                type: string
        "400":
          $ref: ../responses/system/DownloadSourceCodeAccessError.yaml
  /permissions:
    get:
      operationId: getPermissions
      summary: Get Permissions
      description: "**REQUIRES ADMIN CREDENTIALS**. Returns a list of all existing permissions, just like `/users` with empty search would."
      tags:
        - miscellaneous
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/permissions/PermissionListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/InvalidAdminCredentialsError.yaml
      x-internal: true
    post:
      operationId: createPermission
      summary: Create Permission
      x-internal: true
      description: "**REQUIRES ADMIN CREDENTIALS**. Creates and returns a new Permission. The permission will by default be owned by the sender of the request unless otherwise specified."
      tags:
        - miscellaneous
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
        - name: ownerId
          description: "Owner of the Permission, MUST be valid UserID."
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ownerId:
                  $ref: ../schemas/UserID.yaml
              required:
                - name
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/permissions/PermissionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/InvalidAdminCredentialsError.yaml
  "/permissions/{permissionId}":
    parameters:
      - $ref: ../parameters.yaml#/permissionId
    get:
      operationId: getPermission
      summary: Get Permission
      description: "Returns a single permission. This endpoint is pretty useless, as it returns the exact same information as `/auth/permissions`."
      tags:
        - miscellaneous
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/permissions/PermissionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    put:
      operationId: updatePermission
      summary: Update Permission
      x-internal: true
      description: "**REQUIRES ADMIN CREDENTIALS**. Updates the info on a permission."
      tags:
        - miscellaneous
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ownerId:
                  $ref: ../schemas/UserID.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/permissions/PermissionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/InvalidAdminCredentialsError.yaml
    delete:
      operationId: deletePermission
      summary: Delete Permission
      description: "**REQUIRES ADMIN CREDENTIALS**. Deletes a permission."
      x-internal: true
      tags:
        - miscellaneous
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/permissions/PermissionResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/InvalidAdminCredentialsError.yaml
  /time:
    get:
      operationId: getSystemTime
      summary: Current System Time
      description: |-
        Returns the current time of the API server.

        **NOTE:** The response type is not a JSON object, but a simple JSON string.
      tags:
        - miscellaneous
      security: []
      responses:
        "200":
          $ref: ../responses/system/SystemTimeResponse.yaml
  /visits:
    get:
      operationId: getCurrentOnlineUsers
      summary: Current Online Users
      description: |-
        Returns the current number of online users.

        **NOTE:** The response type is not a JSON object, but a simple JSON integer.
      tags:
        - miscellaneous
      security: []
      responses:
        "200":
          $ref: ../responses/system/CurrentOnlineUsersResponse.yaml
tags:
  $ref: ../tags.yaml
