openapi: 3.0.3
info:
  title: notifications
  version: '1.0'
  description: Notifiations Docs
paths:
  /auth/user/notifications:
    get:
      summary: List Notifications
      tags:
        - notifications
      x-codeSamples:
        $ref: "../codeSamples/notifications.yaml#/~1auth~1user~1notifications/get"
      responses:
        '200':
          $ref: ../responses/notifications/NotificationListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getNotifications
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Retrieve all of the current user's notifications.
      parameters:
        - schema:
            type: string
            example: all
          in: query
          name: type
          description: Only send notifications of this type (can use `all` for all).
          deprecated: true
        - schema:
            type: boolean
          in: query
          name: sent
          description: Return notifications sent by the user. Must be false or omitted.
          deprecated: true
        - schema:
            type: boolean
          in: query
          name: hidden
          description: Whether to return hidden or non-hidden notifications. True only allowed on type `friendRequest`.
        - schema:
            type: string
            example: five_minutes_ago
          in: query
          name: after
          description: Only return notifications sent after this Date. Ignored if type is `friendRequest`.
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
  '/auth/user/notifications/{notificationId}/see':
    parameters:
      - $ref: ../parameters.yaml#/notificationId
    put:
      summary: Mark Notification As Read
      operationId: markNotificationAsRead
      x-codeSamples:
        $ref: "../codeSamples/notifications.yaml#/~1auth~1user~1notifications~1{notificationId}~1see/put"
      responses:
        '200':
          $ref: ../responses/notifications/NotificationResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Mark a notification as seen.
      tags:
        - notifications
  '/auth/user/notifications/{notificationId}/hide':
    parameters:
      - $ref: ../parameters.yaml#/notificationId
    put:
      summary: Delete Notification
      operationId: deleteNotification
      x-codeSamples:
        $ref: "../codeSamples/notifications.yaml#/~1auth~1user~1notifications~1{notificationId}~1hide/put"
      responses:
        '200':
          $ref: ../responses/notifications/NotificationResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Delete a notification.
      tags:
        - notifications
  '/auth/user/notifications/{notificationId}/accept':
    parameters:
      - $ref: ../parameters.yaml#/notificationId
    put:
      summary: Accept Friend Request
      operationId: acceptFriendRequest
      x-codeSamples:
        $ref: "../codeSamples/notifications.yaml#/~1auth~1user~1notifications~1{notificationId}~1accept/put"
      responses:
        '200':
          $ref: ../responses/friends/FriendSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/friends/AcceptFriendRequestError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Accept a friend request by notification `frq_` ID. Friend requests can be found using the NotificationsAPI `getNotifications` by filtering of type `friendRequest`.
      tags:
        - notifications
  /auth/user/notifications/clear:
    put:
      summary: Clear All Notifications
      operationId: clearNotifications
      x-codeSamples:
        $ref: "../codeSamples/notifications.yaml#/~1auth~1user~1notifications~1notifications~1clear/put"
      responses:
        '200':
          $ref: ../responses/notifications/ClearNotificationsSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Clear **all** notifications.
      tags:
        - notifications
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml