openapi: 3.0.3
info:
  title: prints
  description: Prints are a way to print photos directly from the VRChat camera.
  version: "1.0"
paths:
  /prints:
    post:
      operationId: uploadPrint
      summary: Upload Print
      description: Uploads and creates a print.
      tags:
        - prints
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  description: The binary blob of the png file.
                  format: binary
                note:
                  type: string
                  description: The caption for the image.
                timestamp:
                  type: string
                  description: The time the image was captured.
                  format: date-time
                worldId:
                  type: string
                  description: The id of the world in which the image was captured.
                worldName:
                  type: string
                  description: The name of the world in which the image was captured.
              required:
                - image
                - timestamp
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/prints/PrintResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /prints/user/{userId}:
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserPrints
      summary: Get Own Prints
      description: Returns a list of all prints of the user. User id has to be your own userId, as you can't request other user's prints.
      tags:
        - prints
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/prints/PrintListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/prints/UnableToRequestOtherUsersPrintsError.yaml
  /prints/{printId}:
    parameters:
      - $ref: ../parameters.yaml#/printId
    get:
      operationId: getPrint
      summary: Get Print
      description: Returns a print.
      tags:
        - prints
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/prints/PrintResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    post:
      operationId: editPrint
      summary: Edit Print
      description: Edits a print.
      tags:
        - prints
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  description: The binary blob of the png file.
                  format: binary
                note:
                  type: string
                  description: The caption for the image.
              required:
                - image
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/prints/PrintResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    delete:
      operationId: deletePrint
      summary: Delete Print
      description: Returns a print.
      tags:
        - prints
      security:
        - authCookie: []
      responses:
        "200":
          description: Empty response if successful
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
tags:
  $ref: ../tags.yaml
