openapi: 3.0.3
info:
  title: props
  description: Props are interactable items users can spawn into instances.
  version: "1.0"
paths:
  "/props/{propId}":
    parameters:
      - $ref: ../parameters.yaml#/propId
    get:
      operationId: getProp
      summary: Get Prop
      description: Returns a Prop object.
      tags:
        - props
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/props/PropResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
tags:
  $ref: ../tags.yaml
