openapi: 3.0.3
info:
  title: system
  version: '1.0'
  description: System Docs Here
paths:
  /infoPush:
    get:
      summary: Show Information Notices
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1infoPush/get"
      responses:
        '200':
          $ref: ../responses/system/InfoPushListResponse.yaml
      operationId: getInfoPush
      description: |-
        IPS (Info Push System) is a system for VRChat to push out dynamic information to the client. This is primarily used by the Quick-Menu info banners, but can also be used to e.g. alert you to update your game to the latest version.

        `include` is used to query what Information Pushes should be included in the response. If include is missing or empty, then no notices will normally be returned. This is an "any of" search.

        `require` is used to limit what Information Pushes should be included in the response. This is usually used in combination with `include`, and is an "all of" search.
      parameters:
        - $ref: ../parameters.yaml#/require
        - $ref: ../parameters.yaml#/include
      x-badges:
        - color: gold
          label: 'Status: Early Access (Still Under Development)'
  /jams:
    get:
      summary: Show jams list
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1jams/get"
      responses:
        '200':
          $ref: ../responses/system/JamListResponse.yaml
      security:
        - authCookie: []
      operationId: getJams
      description: |-
        Lists World Jams or Avatar Jams, both currently running and ones that have ended.
        
        `isActive` is used to select only active or already ended jams.
        
        `type` is used to select only world or avatar jams, and can only take `world` or `avatar`.
        ``
      parameters:
        - schema:
            type: boolean
            example: false
          in: query
          name: isActive
          description: 'Only show jams that are currently active or have already ended.'
        - schema:
            type: string
            example: avatar
          in: query
          name: type
          description: 'Only show jams of this type (`avatar` or `world`).'
  /jams/{jamId}:
    parameters:
      - $ref: ../parameters.yaml#/jamId
    get:
      summary: Show jam information
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1jams~1{jamId}/get"
      responses:
        '200':
          $ref: ../responses/system/JamResponse.yaml
        '404':
          $ref: ../responses/system/JamNotFoundError.yaml
      security:
        - authCookie: []
      operationId: getJam
      description: Returns a jam.
  /jams/{jamId}/submissions:
    parameters:
      - $ref: ../parameters.yaml#/jamId
    get:
      summary: Show jam submissions
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1jams~1{jamId}~1submissions/get"
      responses:
        '200':
          $ref: ../responses/system/SubmissionListResponse.yaml
        '404':
          $ref: ../responses/system/JamNotFoundError.yaml
      security:
        - authCookie: []
      operationId: getJamSubmissions
      description: Returns all submissions of a jam.
  /health:
    get:
      summary: Check API Health
      tags:
        - system
      operationId: getHealth
      description: |-
        ~~Gets the overall health status, the server name, and the current build version tag of the API.~~

        **DEPRECATED:** VRChat has suddenly restricted this endpoint for unknown reasons, and now always return 401 Unauthorized.
      security: []
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1health/get"
      responses:
        '200':
          $ref: ../responses/system/APIHealthResponse.yaml
      deprecated: true
  /config:
    get:
      summary: Fetch API Config
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1config/get"
      responses:
        '200':
          $ref: ../responses/system/APIConfigResponse.yaml
      operationId: getConfig
      description: |-
        API config contains configuration that the clients needs to work properly.

        Currently the most important value here is `clientApiKey` which is used for all other API endpoints.
      security: []
  /visits:
    get:
      summary: Current Online Users
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1visits/get"
      responses:
        '200':
          $ref: ../responses/system/CurrentOnlineUsersResponse.yaml
      operationId: getCurrentOnlineUsers
      security: []
      description: |-
        Returns the current number of online users.

        **NOTE:** The response type is not a JSON object, but a simple JSON integer.
  /time:
    get:
      summary: Current System Time
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1time/get"
      responses:
        '200':
          $ref: ../responses/system/SystemTimeResponse.yaml
      operationId: getSystemTime
      description: |-
        Returns the current time of the API server.

        **NOTE:** The response type is not a JSON object, but a simple JSON string.
      security: []
  /js/app.js:
    get:
      summary: Download JavaScript
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1js~1app.js/get"
      responses:
        '200':
          description: '**Note:** VRChat uses 302 Redirect to Cloudfront. The implementing library **must** support and follow redirects natively.'
          content:
            application/javascript:
              schema:
                type: string
        '400':
          $ref: ../responses/system/DownloadSourceCodeAccessError.yaml
      operationId: getJavaScript
      description: Fetches the JavaScript code to the frontend React website.
      parameters:
        - $ref: ../parameters.yaml#/variant
        - $ref: ../parameters.yaml#/branch
  /css/app.css:
    get:
      summary: Download CSS
      tags:
        - system
      x-codeSamples:
        $ref: "../codeSamples/system.yaml#/~1css~1app.css/get"
      responses:
        '200':
          description: '**Note:** VRChat uses 302 Redirect to Cloudfront. The implementing library **must** support and follow redirects natively.'
          content:
            text/css:
              schema:
                type: string
        '400':
          $ref: ../responses/system/DownloadSourceCodeAccessError.yaml
      operationId: getCSS
      description: Fetches the CSS code to the frontend React website.
      parameters:
        - $ref: ../parameters.yaml#/variant
        - $ref: ../parameters.yaml#/branch
tags:
  $ref: ../tags.yaml
