openapi: 3.0.3
info:
  title: users
  description: Users Docs Here
  version: "1.0"
paths:
  /userNotes:
    get:
      operationId: getUserNotes
      summary: Get User Notes
      description: Get recently updated user notes
      tags:
        - users
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/UserNoteListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    post:
      operationId: updateUserNote
      summary: Update User Note
      description: Updates the currently authenticated user's note on a user
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateUserNoteRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/UserNoteResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/userNotes/{userNoteId}":
    parameters:
      - $ref: ../parameters.yaml#/userNoteId
    get:
      operationId: getUserNote
      summary: Get User Note
      description: Get a particular user note
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/UserNoteResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /users:
    get:
      operationId: searchUsers
      summary: Search All Users
      description: Search and list any users by text query
      tags:
        - users
      parameters:
        - name: search
          description: Searches by `displayName`. Will return empty array if search query is empty or missing.
          in: query
          schema:
            type: string
            minLength: 0
        - name: developerType
          description: "Active user by developer type, none for normal users and internal for moderators"
          in: query
          schema:
            type: string
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/LimitedUserSearchListResponse.yaml
        "400":
          $ref: ../responses/users/UsersInvalidSearchError.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  /users/active:
    get:
      operationId: searchActiveUsers
      x-internal: true
      deprecated: true
      summary: Search Active Users
      description: "**REQUIRES ADMIN CREDENTIALS**. Search and list any Active users by text query."
      tags:
        - users
      parameters:
        - name: search
          description: Username to search for
          required: true
          in: query
          schema:
            type: string
        - name: developerType
          description: "Active user by developer type, none for normal users and internal for moderators"
          in: query
          schema:
            type: string
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/number
      security:
        - authCookie: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../schemas/LimitedUserFriend.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/InvalidAdminCredentialsError.yaml
  "/users/{userId}":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUser
      summary: Get User by ID
      description: Get public user information about a specific user using their ID.
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/UserResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
    put:
      operationId: updateUser
      summary: Update User Info
      description: Update a users information such as the email and birthday.
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateUserRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/CurrentUserResponse.yaml
        "400":
          $ref: ../responses/users/CurrentPasswordRequiredError.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/addTags":
    parameters:
      - $ref: ../parameters.yaml#/userId
    post:
      operationId: addTags
      summary: Add User Tags
      description: Adds tags to the user's profile
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/ChangeUserTagsRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/CurrentUserResponse.yaml
        "400":
          $ref: ../responses/users/UserTagInvalidError.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/badges/{badgeId}":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/badgeId
    put:
      operationId: updateBadge
      summary: Update User Badge
      description: Updates a user's badge
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateUserBadgeRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          description: The user's badge is updated.
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/users/UserMustBeOwnError.yaml
        "404":
          description: The user does not have the badge.
  "/users/{userId}/feedback":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/contentId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
    get:
      operationId: getUserFeedback
      deprecated: true
      summary: Get User Feedback
      description: Get user's submitted feedback
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/FeedbackListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/groups":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserGroups
      summary: Get User Groups
      description: Get user's public groups
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/LimitedUserGroupListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/groups/invited":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserGroupInvites
      summary: Get User Group Invited
      description: Returns a list of Groups the user has been invited to.
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/groups/GroupListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/groups/permissions":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserAllGroupPermissions
      summary: Get user's permissions for all joined groups.
      description: Returns a mapping of GroupIDs to arrays of GroupPermissions.
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: ../schemas/UserAllGroupPermissionsResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/groups/represented":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserRepresentedGroup
      summary: Get user's current represented group
      description: Returns the current group that the user is currently representing
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: ../schemas/representedGroup.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/groups/requested":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserGroupRequests
      summary: Get User Group Requests
      description: Returns a list of Groups the user has requested to be invited into.
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/groups/GroupListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/groups/userblocked":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserGroupBlocks
      summary: Get User Group Blocks
      description: Returns a list of Groups the user has blocked.
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/groups/GroupListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/instances/groups":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getUserGroupInstances
      summary: Get User Group Instances
      description: Returns a list of group instances for a user
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/UserGroupInstanceListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/users/UserMustBeOwnError.yaml
  "/users/{userId}/instances/groups/{groupId}":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/groupId
    get:
      operationId: getUserGroupInstancesForGroup
      summary: Get User Group Instances for a specific Group
      description: Returns a list of a group's instances for a user
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/UserGroupInstanceListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "403":
          $ref: ../responses/users/UserMustBeOwnError.yaml
  "/users/{userId}/mutuals":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      operationId: getMutuals
      summary: Get User Mutuals
      description: Gets the counts of mutuals between the logged in user and the specified user
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/MutualsResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/mutuals/friends":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
    get:
      operationId: getMutualFriends
      summary: Get User Mutual Friends
      description: Gets a list of mutual friends between the logged in user and the specified user
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/MutualFriendListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/mutuals/groups":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
    get:
      operationId: getMutualGroups
      summary: Get User Mutual Groups
      description: Gets a list of mutual groups between the logged in user and the specified user
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/LimitedUserGroupListResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/persist":
    parameters:
      - $ref: ../parameters.yaml#/userId
    delete:
      operationId: deleteAllUserPersistenceData
      summary: Delete All User Persistence Data
      description: Deletes all of the user's persistence data for every world.
      tags:
        - users
        - worlds
      security:
        - authCookie: []
      responses:
        "200":
          description: The user's persistence data for all worlds is deleted.
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/removeTags":
    parameters:
      - $ref: ../parameters.yaml#/userId
    post:
      operationId: removeTags
      summary: Remove User Tags
      description: Removes tags from the user's profile
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/ChangeUserTagsRequest.yaml
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/CurrentUserResponse.yaml
        "400":
          $ref: ../responses/users/UserTagInvalidError.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
  "/users/{userId}/{worldId}/persist":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/worldId
    delete:
      operationId: deleteUserPersistence
      summary: Delete User Persistence
      description: Deletes the user's persistence data for a given world
      tags:
        - users
        - worlds
      security:
        - authCookie: []
      responses:
        "200":
          description: The user's persistence data for the given world is deleted.
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "404":
          description: The user does not have persistence data for the given world.
  "/users/{userId}/{worldId}/persist/exists":
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/worldId
    get:
      operationId: checkUserPersistenceExists
      summary: Check User Persistence Exists
      description: Checks whether the user has persistence data for a given world
      tags:
        - users
        - worlds
      security:
        - authCookie: []
      responses:
        "200":
          description: The user has persistence data for the given world.
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
        "404":
          description: The user does not have persistence data for the given world.
  "/users/{username}/name":
    parameters:
      - name: username
        description: Username of the user
        required: true
        in: path
        schema:
          type: string
    get:
      operationId: getUserByName
      deprecated: true
      summary: Get User by Username
      description: |-
        ~~Get public user information about a specific user using their name.~~

        **DEPRECATED:** VRChat API no longer return usernames of other users. [See issue by Tupper for more information](https://github.com/pypy-vrc/VRCX/issues/429).
        This endpoint now require Admin Credentials.
      tags:
        - users
      security:
        - authCookie: []
      responses:
        "200":
          $ref: ../responses/users/UserResponse.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
tags:
  $ref: ../tags.yaml
