openapi: 3.0.3
info:
  title: users
  version: '1.0'
  description: Users Docs Here
paths:
  /users:
    get:
      summary: Search All Users
      tags:
        - users
      x-codeSamples:
        $ref: "../codeSamples/users.yaml#/~1users/get"
      responses:
        '200':
          $ref: ../responses/users/LimitedUserListResponse.yaml
        '400':
          $ref: ../responses/users/UsersInvalidSearchError.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: searchUsers
      security:
        - apiKeyCookie: []
          authCookie: []
      parameters:
        - schema:
            type: string
            minLength: 0
          in: query
          name: search
          description: Searches by `displayName`. Will return empty array if search query is empty or missing.
        - schema:
            type: string
          in: query
          name: developerType
          description: 'Active user by developer type, none for normal users and internal for moderators'
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      description: Search and list any users by text query
  '/users/{username}/name':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
    get:
      summary: Get User by Username
      tags:
        - users
      x-codeSamples:
        $ref: "../codeSamples/users.yaml#/~1users~1{username}~1name/get"
      responses:
        '200':
          $ref: ../responses/users/UserResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUserByName
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Get public user information about a specific user using their name.
  '/users/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get User by ID
      tags:
        - users
      x-codeSamples:
        $ref: "../codeSamples/users.yaml#/~1users~1{userId}/get"
      responses:
        '200':
          $ref: ../responses/users/UserResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUser
      security:
        - apiKeyCookie: []
          apiKeyQuery: []
          authCookie: []
      description: Get public user information about a specific user using their ID.
    put:
      summary: Update User Info
      operationId: updateUser
      x-codeSamples:
        $ref: "../codeSamples/users.yaml#/~1users~1{userId}/put"
      responses:
        '200':
          $ref: ../responses/users/CurrentUserResponse.yaml
      description: Update a users information such as the email and birthday.
      security:
        - apiKeyCookie: []
          authCookie: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateUserRequest.yaml
      tags:
        - users
  /users/active:
    get:
      summary: Search Active Users
      tags:
        - users
      x-codeSamples:
        $ref: "../codeSamples/users.yaml#/~1users~1active/get"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../schemas/LimitedUser.yaml
        '403':
          $ref: ../responses/InvalidAdminCredentialsError.yaml
      operationId: searchActiveUsers
      security:
        - apiKeyCookie: []
          authCookie: []
      parameters:
        - schema:
            type: string
          in: query
          name: search
          required: true
          description: Username to search for
        - schema:
            type: string
          in: query
          name: developerType
          description: 'Active user by developer type, none for normal users and internal for moderators'
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/number
      x-internal: true
      deprecated: true
      description: '**REQUIRES ADMIN CREDENTIALS**. Search and list any Active users by text query.'
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
