openapi: 3.0.3
info:
  title: users
  version: '1.0'
  description: Users Docs Here
paths:
  /users:
    get:
      summary: Search All Users
      tags:
        - users
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users/get
      responses:
        '200':
          $ref: ../responses/users/LimitedUserListResponse.yaml
        '400':
          $ref: ../responses/users/UsersInvalidSearchError.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: searchUsers
      security:
        - authCookie: []
      parameters:
        - schema:
            type: string
            minLength: 0
          in: query
          name: search
          description: Searches by `displayName`. Will return empty array if search query is empty or missing.
        - schema:
            type: string
          in: query
          name: developerType
          description: 'Active user by developer type, none for normal users and internal for moderators'
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      description: Search and list any users by text query
  '/users/{username}/name':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
        description: Username of the user
    get:
      summary: Get User by Username
      tags:
        - users
      x-codeSamples:
        $ref: '../codeSamples/users.yaml#/~1users~1{username}~1name/get'
      responses:
        '200':
          $ref: ../responses/users/UserResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUserByName
      security:
        - authCookie: []
      description: |-
        ~~Get public user information about a specific user using their name.~~

        **DEPRECATED:** VRChat API no longer return usernames of other users. [See issue by Tupper for more information](https://github.com/pypy-vrc/VRCX/issues/429).
        This endpoint now require Admin Credentials.
      deprecated: true
  '/users/{userId}':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get User by ID
      tags:
        - users
      x-codeSamples:
        $ref: '../codeSamples/users.yaml#/~1users~1{userId}/get'
      responses:
        '200':
          $ref: ../responses/users/UserResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUser
      security:
        - authCookie: []
      description: Get public user information about a specific user using their ID.
    put:
      summary: Update User Info
      operationId: updateUser
      x-codeSamples:
        $ref: '../codeSamples/users.yaml#/~1users~1{userId}/put'
      responses:
        '200':
          $ref: ../responses/users/CurrentUserResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      description: Update a users information such as the email and birthday.
      security:
        - authCookie: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateUserRequest.yaml
      tags:
        - users
  '/users/{userId}/groups':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get User Groups
      tags:
        - users
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/users/LimitedUserGroupListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUserGroups
      description: Get user's public groups
  /users/active:
    get:
      summary: Search Active Users
      tags:
        - users
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1active/get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../schemas/LimitedUser.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '403':
          $ref: ../responses/InvalidAdminCredentialsError.yaml
      operationId: searchActiveUsers
      security:
        - authCookie: []
      parameters:
        - schema:
            type: string
          in: query
          name: search
          required: true
          description: Username to search for
        - schema:
            type: string
          in: query
          name: developerType
          description: 'Active user by developer type, none for normal users and internal for moderators'
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/number
      x-internal: true
      deprecated: true
      description: '**REQUIRES ADMIN CREDENTIALS**. Search and list any Active users by text query.'
  '/users/{userId}/groups/requested':
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get User Group Requests
      description: Returns a list of Groups the user has requested to be invited into.
      operationId: getUserGroupRequests
      tags:
        - users
      responses:
        '200':
          $ref: ../responses/groups/GroupListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - authCookie: []
  "/users/{userId}/groups/represented":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get user's current represented group
      description: Returns the current group that the user is currently representing
      operationId: getUserRepresentedGroup
      tags:
        - users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: ../schemas/representedGroup.yaml
        "401":
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - authCookie: []
  '/users/{userId}/feedback':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/contentId
      - $ref: ../parameters.yaml#/number
      - $ref: ../parameters.yaml#/offset
    get:
      summary: Get User Feedback
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1{userId}~1feedback/get
      tags:
        - users
      deprecated: true
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/users/FeedbackListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUserFeedback
      description: Get user's submitted feedback
  '/userNotes':
    get:
      summary: Get User Notes
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1userNotes/get
      tags:
        - users
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/users/UserNoteListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUserNotes
      parameters:
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/offset
      description: Get recently updated user notes
    post:
      summary: Update User Note
      tags:
        - users
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1userNotes/post
      responses:
        '200':
          $ref: ../responses/users/UserNoteResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: updateUserNote
      security:
        - authCookie: []
      description: Updates the currently authenticated user's note on a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateUserNoteRequest.yaml
  '/userNotes/{userNoteId}':
    parameters:
      - $ref: ../parameters.yaml#/userNoteId
    get:
      summary: Get User Note
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1userNotes~1{userNoteId}/get
      tags:
        - users
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/users/UserNoteResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getUserNote
      description: Get a particular user note
  '/users/{userId}/addTags':
    parameters:
      - $ref: ../parameters.yaml#/userId
    post:
      summary: Add User Tags
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1{userId}~1addTags/post
      description: Adds tags to the user's profile
      operationId: addTags
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/ChangeUserTagsRequest.yaml
      responses:
        '200':
          $ref: ../responses/users/CurrentUserResponse.yaml
        '400':
          $ref: ../responses/users/UserTagInvalidError.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - authCookie: []
  '/users/{userId}/removeTags':
    parameters:
      - $ref: ../parameters.yaml#/userId
    post:
      summary: Remove User Tags
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1{userId}~1removeTags/post
      description: Removes tags from the user's profile
      operationId: removeTags
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/ChangeUserTagsRequest.yaml
      responses:
        '200':
          $ref: ../responses/users/CurrentUserResponse.yaml
        '400':
          $ref: ../responses/users/UserTagInvalidError.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      security:
        - authCookie: []
  '/users/{userId}/badges/{badgeId}':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/badgeId
    put:
      summary: Update User Badge
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1{userId}~1badges~1{badgeId}/put
      description: Updates a user's badge
      operationId: updateBadge
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateUserBadgeRequest.yaml
      responses:
        '200':
          description: The user's badge is updated.
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '403':
          $ref: ../responses/users/UserMustBeOwnError.yaml
        '404':
          description: The user does not have the badge.
      security:
        - authCookie: []
  "/users/{userId}/instances/groups":
    parameters:
      - $ref: ../parameters.yaml#/userId
    get:
      summary: Get User Group Instances
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1{userId}~1instances~1groups/get
      description: Returns a list of group instances for a user
      operationId: getUserGroupInstances
      tags:
        - users
      responses:
        '200':
          $ref: ../responses/users/UserGroupInstanceListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '403':
          $ref: ../responses/users/UserMustBeOwnError.yaml
      security:
        - authCookie: []
  '/users/{userId}/{worldId}/persist/exists':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/worldId
    get:
      summary: Check User Persistence Exists
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1{userId}~1{worldId}~1persist~1exists/get
      description: Checks whether the user has persistence data for a given world
      operationId: checkUserPersistenceExists
      tags:
        - users
        - worlds
      responses:
        '200':
          description: The user has persistence data for the given world.
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          description: The user does not have persistence data for the given world.
      security:
        - authCookie: []
  '/users/{userId}/{worldId}/persist':
    parameters:
      - $ref: ../parameters.yaml#/userId
      - $ref: ../parameters.yaml#/worldId
    delete:
      summary: Delete User Persistence
      x-codeSamples:
        $ref: ../codeSamples/users.yaml#/~1users~1{userId}~1{worldId}~1persist/delete
      description: Deletes the user's persistence data for a given world
      operationId: deleteUserPersistence
      tags:
        - users
        - worlds
      responses:
        '200':
          description: The user's persistence data for the given world is deleted.
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          description: The user does not have persistence data for the given world.
      security:
        - authCookie: []
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
