openapi: 3.0.3
info:
  title: worlds
  version: '1.0'
  description: Worlds Docs Here
paths:
  /worlds:
    get:
      summary: Search All Worlds
      tags:
        - worlds
      responses:
        '200':
          $ref: ../responses/worlds/LimitedWorldListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: searchWorlds
      security:
        - authCookie: []
      parameters:
        - $ref: ../parameters.yaml#/featured
        - $ref: ../parameters.yaml#/sort
        - schema:
            type: string
            enum:
              - me
          in: query
          required: false
          name: user
          description: Set to `me` for searching own worlds.
        - $ref: ../parameters.yaml#/userIdQuery
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/order
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/search
        - $ref: ../parameters.yaml#/tag
        - $ref: ../parameters.yaml#/notag
        - $ref: ../parameters.yaml#/releaseStatus
        - $ref: ../parameters.yaml#/maxUnityVersion
        - $ref: ../parameters.yaml#/minUnityVersion
        - $ref: ../parameters.yaml#/platform
        - $ref: ../parameters.yaml#/noplatform
        - $ref: ../parameters.yaml#/fuzzy
        - $ref: ../parameters.yaml#/avatarSpecific
      description: Search and list any worlds by query filters.
    post:
      summary: Create World
      operationId: createWorld
      responses:
        '200':
          $ref: ../responses/worlds/WorldResponse.yaml
        '400':
          $ref: ../responses/worlds/WorldCreateNotAllowedYetError.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/CreateWorldRequest.yaml
        description: ''
      description: 'Create a new world. This endpoint requires `assetUrl` to be a valid File object with `.vrcw` file extension, and `imageUrl` to be a valid File object with an image file extension.'
      tags:
        - worlds
  /worlds/active:
    get:
      summary: List Active Worlds
      tags:
        - worlds
      responses:
        '200':
          $ref: ../responses/worlds/LimitedWorldListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
      operationId: getActiveWorlds
      security:
        - authCookie: []
      parameters:
        - $ref: ../parameters.yaml#/featured
        - $ref: ../parameters.yaml#/sort
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/order
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/search
        - $ref: ../parameters.yaml#/tag
        - $ref: ../parameters.yaml#/notag
        - $ref: ../parameters.yaml#/releaseStatus
        - $ref: ../parameters.yaml#/maxUnityVersion
        - $ref: ../parameters.yaml#/minUnityVersion
        - $ref: ../parameters.yaml#/platform
        - $ref: ../parameters.yaml#/noplatform
      description: Search and list currently Active worlds by query filters.
  /worlds/recent:
    get:
      summary: List Recent Worlds
      tags:
        - worlds
      responses:
        '200':
          $ref: ../responses/worlds/LimitedWorldListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '403':
          $ref: ../responses/worlds/WorldSeeOtherUserRecentsError.yaml
      operationId: getRecentWorlds
      security:
        - authCookie: []
      parameters:
        - $ref: ../parameters.yaml#/featured
        - $ref: ../parameters.yaml#/sort
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/order
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/search
        - $ref: ../parameters.yaml#/tag
        - $ref: ../parameters.yaml#/notag
        - $ref: ../parameters.yaml#/releaseStatus
        - $ref: ../parameters.yaml#/maxUnityVersion
        - $ref: ../parameters.yaml#/minUnityVersion
        - $ref: ../parameters.yaml#/platform
        - $ref: ../parameters.yaml#/userIdAdmin
      description: Search and list recently visited worlds by query filters.
  /worlds/favorites:
    get:
      summary: List Favorited Worlds
      tags:
        - worlds
      responses:
        '200':
          $ref: ../responses/worlds/FavoritedWorldListResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '403':
          $ref: ../responses/worlds/WorldSeeOtherUserFavoritesError.yaml
      operationId: getFavoritedWorlds
      security:
        - authCookie: []
      parameters:
        - $ref: ../parameters.yaml#/featured
        - $ref: ../parameters.yaml#/sort
        - $ref: ../parameters.yaml#/number
        - $ref: ../parameters.yaml#/order
        - $ref: ../parameters.yaml#/offset
        - $ref: ../parameters.yaml#/search
        - $ref: ../parameters.yaml#/tag
        - $ref: ../parameters.yaml#/notag
        - $ref: ../parameters.yaml#/releaseStatus
        - $ref: ../parameters.yaml#/maxUnityVersion
        - $ref: ../parameters.yaml#/minUnityVersion
        - $ref: ../parameters.yaml#/platform
        - $ref: ../parameters.yaml#/userIdAdmin
      description: Search and list favorited worlds by query filters.
  '/worlds/{worldId}':
    parameters:
      - $ref: ../parameters.yaml#/worldId
    get:
      summary: Get World by ID
      tags:
        - worlds
      operationId: getWorld
      responses:
        '200':
          $ref: ../responses/worlds/WorldResponse.yaml
        '404':
          $ref: ../responses/worlds/WorldNotFoundError.yaml
      description: |-
        Get information about a specific World.
        Works unauthenticated but when so will always return `0` for certain fields.
    put:
      summary: Update World
      operationId: updateWorld
      security:
        - authCookie: []
      responses:
        '200':
          $ref: ../responses/worlds/WorldResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/worlds/WorldNotFoundError.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../requests/UpdateWorldRequest.yaml
      description: Update information about a specific World.
      tags:
        - worlds
    delete:
      summary: Delete World
      operationId: deleteWorld
      security:
        - authCookie: []
      responses:
        '200':
          description: OK
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/worlds/WorldNotFoundError.yaml
      description: 'Delete a world. Notice a world is never fully "deleted", only its ReleaseStatus is set to "hidden" and the linked Files are deleted. The WorldID is permanently reserved.'
      tags:
        - worlds
  '/worlds/{worldId}/{instanceId}':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    get:
      summary: Get World Instance
      tags:
        - worlds
      operationId: getWorldInstance
      security:
        - authCookie: []
      description: Returns a worlds instance.
      responses:
        '200':
          $ref: ../responses/instances/InstanceResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
  '/worlds/{worldId}/metadata':
    parameters:
      - $ref: ../parameters.yaml#/worldId
    get:
      summary: Get World Metadata
      tags:
        - worlds
      operationId: getWorldMetadata
      security:
        - authCookie: []
      deprecated: true
      description: Return a worlds custom metadata. This is currently believed to be unused. Metadata can be set with `updateWorld` and can be any arbitrary object.
      responses:
        '200':
          $ref: ../responses/worlds/WorldMetadataResponse.yaml
        '404':
          $ref: ../responses/worlds/WorldNotFoundError.yaml
  '/worlds/{worldId}/publish':
    parameters:
      - $ref: ../parameters.yaml#/worldId
    get:
      summary: Get World Publish Status
      tags:
        - worlds
      operationId: getWorldPublishStatus
      security:
        - authCookie: []
      description: Returns a worlds publish status.
      responses:
        '200':
          $ref: ../responses/worlds/WorldPublishStatusResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/worlds/WorldNotFoundError.yaml
    put:
      summary: Publish World
      operationId: publishWorld
      security:
        - authCookie: []
      responses:
        '200':
          description: TODO
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/worlds/WorldNotFoundError.yaml
      description: Publish a world. You can only publish one world per week.
      tags:
        - worlds
    delete:
      summary: Unpublish World
      operationId: unpublishWorld
      security:
        - authCookie: []
      responses:
        '200':
          description: OK
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/worlds/WorldNotFoundError.yaml
      description: Unpublish a world.
      tags:
        - worlds
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
