# See https://redoc.ly/docs/cli/configuration/ for more information.
extends:
  - recommended

apis:
  main:
    root: openapi/openapi.yaml

plugins:
  - "./.github/redocly-plugins/remove-internal.js"
  - "./.github/redocly-plugins/x-feature.js"
decorators:
  remove-internal/remove-internal: error
  x-feature/fallback-replace:
    available_features: [oneOf]
