formats:
  - oas3
extends:
  - 'spectral:oas'
rules:
  oas3-parameter-description: info
  tag-description: hint

  # Rules for sub schema
  info-license: hint
  license-url: hint
  oas3-api-servers: hint
  info-contact: hint