openapi: 3.2.1
info:
  title: VRChat API
  version: 1.21.0
  contact:
    name: VRChat API Community
    url: "https://vrchat.community"
  termsOfService: "https://vrchat.com/legal/"
  license:
    url: "https://github.com/vrchatapi/specification/blob/master/LICENSE"
    name: MIT
servers:
  - url: "https://api.vrchat.cloud/api/1"
paths:
  $ref: ./components/paths.yaml
components:
  schemas:
    $ref: ./components/schemas/_index.yaml
  securitySchemes:
    $ref: ./components/securitySchemes.yaml
  responses: {}
tags:
  $ref: ./components/tags.yaml
