title: APIConfigProfileDefaults
type: object
description: Default profile theme colors.
properties:
  backgroundGradientBottom:
    $ref: ./Color.yaml
  backgroundGradientTop:
    $ref: ./Color.yaml
  themeButtonColor:
    $ref: ./Color.yaml
  themeIconColor:
    $ref: ./Color.yaml
  themeSubtextColor:
    $ref: ./Color.yaml
