example:
  VoiceEnableDegradation: false
  VoiceEnableReceiverLimiting: true
  address: '1062 Folsom St., Suite 200, San Francisco, CA, 94103'
  announcements:
    - name: 220121a_modified_clients
      text: |-
        As part of our continued commitment to improve
        safety and awareness, we want to remind you that
        <color='red'>modified clients of any kind are not allowed
        on VRChat</color>, for any reason, and are prohibited
        by the Terms of Service.

        There is no such thing as an 'approved'
        modification, nor do we permit the use of
        any modification, for any purpose, ever.
        <color='red'>Using them can and will result in your
        account being banned!</color>

        In addition, modified clients are the single
        greatest source of <color='red'>compromised and stolen
        accounts</color>-- so please, do not use them!
  appName: VrChat
  buildVersionTag: master-build-2021-09-23-edith-x-clickbaitcloud
  clientApiKey: JlE5Jldo5Jibnk5O5hTx6XVqsJu4WJ26
  clientBPSCeiling: 18432
  clientDisconnectTimeout: 30000
  clientReservedPlayerBPS: 7168
  clientSentCountAllowance: 15
  contactEmail: hello@vrchat.com
  copyrightEmail: copyright@vrchat.com
  currentTOSVersion: 7
  defaultAvatar: avtr_c38a1615-5bf5-42b4-84eb-a8b6c37cbd11
  deploymentGroup: blue
  devAppVersionStandalone: 0.12.0p3
  devDownloadLinkWindows: www.vrchat.net
  devSdkUrl: 'https://vrchat.com/home/download'
  devSdkVersion: 2020.09.25.00.08
  devServerVersionStandalone: dev_server_01
  dis-countdown: '2021-01-01T01:01:01.000Z'
  disableAvatarCopying: false
  disableAvatarGating: false
  disableCommunityLabs: false
  disableCommunityLabsPromotion: false
  disableEmail: false
  disableEventStream: false
  disableFeedbackGating: false
  disableFrontendBuilds: false
  disableHello: false
  disableOculusSubs: false
  disableRegistration: false
  disableSteamNetworking: true
  disableTwoFactorAuth: false
  disableUdon: false
  disableUpgradeAccount: false
  downloadLinkWindows: 'https://www.oculus.com/experiences/rift/997678176960598/'
  downloadUrls:
    sdk2: 'https://files.vrchat.cloud/sdk/VRCSDK2-2021.09.03.09.25_Public.unitypackage'
    sdk3-avatars: 'https://files.vrchat.cloud/sdk/VRCSDK3-AVATAR-2021.09.03.09.25_Public.unitypackage'
    sdk3-worlds: 'https://files.vrchat.cloud/sdk/VRCSDK3-WORLD-2021.09.03.09.25_Public.unitypackage'
    vcc: 'https://vrcpm.vrchat.cloud/vcc/Builds/2.1.1/VRChat_CreatorCompanion_Setup_2.1.1.exe'
    bootstrap: 'https://github.com/vrchat/packages/releases/download/resolvers/latest-resolver.unitypackage'
  dynamicWorldRows:
    - index: 1
      name: Hot
      platform: ThisPlatformSupported
      sortHeading: heat
      sortOrder: descending
      sortOwnership: any
    - index: 2
      name: 'World Jam: Obstacle Course'
      platform: ThisPlatformSupported
      sortHeading: order
      sortOrder: ascending
      sortOwnership: any
      tag: admin_jam_obstacle
    - index: 3
      name: Exercise
      platform: Any
      sortHeading: shuffle
      sortOrder: descending
      sortOwnership: any
      tag: admin_exercise_row
    - index: 4
      name: Spotlight
      platform: ThisPlatformSupported
      sortHeading: updated
      sortOrder: descending
      sortOwnership: any
      tag: admin_community_spotlight
    - index: 5
      name: Community Labs
      platform: ThisPlatformSupported
      sortHeading: labs
      sortOrder: descending
      sortOwnership: any
    - index: 6
      name: Active Cross Platform
      platform: AllPlatforms
      sortHeading: active
      sortOrder: descending
      sortOwnership: any
    - index: 7
      name: Active My Platform
      platform: ThisPlatformOnly
      sortHeading: active
      sortOrder: descending
      sortOwnership: any
    - index: 8
      name: Random
      platform: ThisPlatformSupported
      sortHeading: shuffle
      sortOrder: descending
      sortOwnership: any
    - index: 9
      name: Avatar Worlds
      platform: ThisPlatformSupported
      sortHeading: heat
      sortOrder: descending
      sortOwnership: any
      tag: author_tag_avatar
    - index: 10
      name: Games
      platform: ThisPlatformSupported
      sortHeading: heat
      sortOrder: descending
      sortOwnership: any
      tag: author_tag_game
    - index: 11
      name: Updated Recently
      platform: ThisPlatformSupported
      sortHeading: updated
      sortOrder: descending
      sortOwnership: any
    - index: 12
      name: New
      platform: ThisPlatformSupported
      sortHeading: publication
      sortOrder: descending
      sortOwnership: any
    - index: 13
      name: Recent
      platform: ThisPlatformSupported
      sortHeading: recent
      sortOrder: descending
      sortOwnership: any
    - index: 14
      name: Mine
      platform: any
      sortHeading: updated
      sortOrder: descending
      sortOwnership: mine
    - index: 15
      name: Classics
      platform: ThisPlatformSupported
      sortHeading: trending
      sortOrder: descending
      sortOwnership: any
  events:
    distanceClose: 2
    distanceFactor: 100
    distanceFar: 80
    groupDistance: 3
    maximumBunchSize: 247
    notVisibleFactor: 100
    playerOrderBucketSize: 5
    playerOrderFactor: 55
    slowUpdateFactorThreshold: 25
    viewSegmentLength: 5
  gearDemoRoomId: '2282253502'
  homeWorldId: wrld_4432ea9b-729c-46e3-8eaf-846aa0a37fdd
  homepageRedirectTarget: 'https://hello.vrchat.com'
  hubWorldId: wrld_ba913a96-fac4-4048-a062-9aa5db092812
  jobsEmail: jobs@vrchat.com
  messageOfTheDay: hello world
  moderationEmail: moderation@vrchat.com
  moderationQueryPeriod: 60
  notAllowedToSelectAvatarInPrivateWorldMessage: 'For security reasons, you''re not yet allowed to select avatars in private worlds or upload content. Please continue to enjoy VRChat and we''ll message you when you''ve been unlocked. Thanks and have fun!'
  plugin: no_kick_unlisted
  releaseAppVersionStandalone: 0.12.0p3
  releaseSdkUrl: 'http://files.vrchat.cloud/sdk/VRCSDK-2019.09.18.12.05_Public.unitypackage'
  releaseSdkVersion: VRCSDK-2019.09.18.12.05_Public
  releaseServerVersionStandalone: public_server_01
  sdkDeveloperFaqUrl: 'https://docs.vrchat.com/docs/frequently-asked-questions#section-why-can-t-i-upload-content-yet-'
  sdkDiscordUrl: 'https://discord.gg/vrchat'
  sdkNotAllowedToPublishMessage: "Welcome the VRChat SDK!\r\n\r\nBefore you can upload avatars or worlds to VRChat, you'll need to spend more time enjoying the app. We do this for security reasons, and so you can learn more about us.\r\n\r\nWhen you get the ability to upload, we will notify you via email and in VRChat. For now, you can learn and test on your own device.\r\n\r\nTo get started, check out the resources below.\r\n\r\nThank you for your patience, we can't wait to see what you'll build!"
  sdkUnityVersion: 2019.4.30f1
  serverName: prod-api-blue-house-fsm
  supportEmail: support@vrchat.com
  timeOutWorldId: wrld_5b89c79e-c340-4510-be1b-476e9fcdedcc
  tutorialWorldId: wld_7d3d25ec-663e-406e-96a3-e2c4fc0d8104
  updateRateMsMaximum: 1000
  updateRateMsMinimum: 50
  updateRateMsNormal: 200
  updateRateMsUdonManual: 50
  uploadAnalysisPercent: 1
  urlList:
    - drive.google.com
    - facebook.com
    - www.facebook.com
    - nicovideo.jp
    - www.nicovideo.jp
    - live.nicovideo.jp
    - live2.nicovideo.jp
    - game.nicovideo.jp
    - soundcloud.com
    - tiktok.com
    - www.tiktok.com
    - twitch.tv
    - www.twitch.tv
    - vimeo.com
    - player.vimeo.com
    - vrchat.cloud
    - youku.com
    - v.youku.com
    - youtube.com
    - www.youtube.com
    - youtu.be
    - assets.vrchat.com
    - www.v-market.work
    - vket6.v-market.work
    - mall.v-market.work
    - cdn.v-market.work
    - movie.cdn.v-market.work
    - wrs.nedo.go.jp
  useReliableUdpForVoice: false
  userUpdatePeriod: 60
  userVerificationDelay: 5
  userVerificationRetry: 30
  userVerificationTimeout: 60
  viveWindowsUrl: 'http://store.steampowered.com/app/438100/'
  whiteListedAssetUrls:
    - 'http://dbinj8iahsbec.cloudfront.net/plugins'
    - 'http://dbinj8iahsbec.cloudfront.net/'
    - 'https://dbinj8iahsbec.cloudfront.net/'
    - 'https://dev-api.vrchat.cloud/api/1/file/'
    - 'https://vrchat.com/api/1/file/'
    - 'https://files.vrchat.cloud/unmanaged/'
  worldUpdatePeriod: 60
  player-url-resolver-hash: E3-C6-63-C3-27-3F-1C-47-48-C6-A7-52-A1-53-03-A5-10-6C-45-37-B1-C3-14-70-BA-44-1F-AE-0E-B2-32-36
  player-url-resolver-version: '2021-05-16'
title: APIConfig
type: object
description: ''
properties:
  VoiceEnableDegradation:
    default: false
    description: 'Unknown, probably voice optimization testing'
    type: boolean
  VoiceEnableReceiverLimiting:
    default: true
    description: 'Unknown, probably voice optimization testing'
    type: boolean
  address:
    description: VRChat's office address
    minLength: 1
    type: string
  announcements:
    type: array
    description: Public Announcements
    uniqueItems: true
    minItems: 0
    items:
      $ref: ./APIConfigAnnouncement.yaml
  appName:
    default: VrChat
    deprecated: true
    description: Game name
    minLength: 1
    type: string
  buildVersionTag:
    description: Build tag of the API server
    minLength: 1
    type: string
  clientApiKey:
    description: apiKey to be used for all other requests
    minLength: 1
    type: string
  clientBPSCeiling:
    default: 18432
    description: Unknown
    type: integer
  clientDisconnectTimeout:
    default: 30000
    description: Unknown
    type: integer
  clientReservedPlayerBPS:
    default: 7168
    description: Unknown
    type: integer
  clientSentCountAllowance:
    default: 15
    description: Unknown
    type: integer
  contactEmail:
    description: VRChat's contact email
    minLength: 1
    type: string
  copyrightEmail:
    description: VRChat's copyright-issues-related email
    minLength: 1
    type: string
  currentTOSVersion:
    example: 7
    description: Current version number of the Terms of Service
    minimum: 0
    type: integer
  defaultAvatar:
    $ref: ./AvatarID.yaml
  deploymentGroup:
    $ref: ./DeploymentGroup.yaml
  devAppVersionStandalone:
    deprecated: true
    description: Version number for game development build
    minLength: 1
    type: string
  devDownloadLinkWindows:
    deprecated: true
    description: Developer Download link
    minLength: 1
    type: string
  devSdkUrl:
    deprecated: true
    description: 'Link to download the development SDK, use downloadUrls instead'
    minLength: 1
    type: string
  devSdkVersion:
    deprecated: true
    description: Version of the development SDK
    minLength: 1
    type: string
  devServerVersionStandalone:
    deprecated: true
    description: Version number for server development build
    minLength: 1
    type: string
  dis-countdown:
    description: 'Unknown, "dis" maybe for disconnect?'
    format: date-time
    type: string
  disableAvatarCopying:
    default: false
    description: Toggles if copying avatars should be disabled
    type: boolean
  disableAvatarGating:
    default: false
    description: Toggles if avatar gating should be disabled. Avatar gating restricts uploading of avatars to people with the `system_avatar_access` Tag or `admin_avatar_access` Tag
    type: boolean
  disableCommunityLabs:
    default: false
    description: Toggles if the Community Labs should be disabled
    type: boolean
  disableCommunityLabsPromotion:
    default: false
    description: Toggles if promotion out of Community Labs should be disabled
    type: boolean
  disableEmail:
    default: false
    description: Unknown
    type: boolean
  disableEventStream:
    default: false
    description: Toggles if Analytics should be disabled.
    type: boolean
  disableFeedbackGating:
    default: false
    description: Toggles if feedback gating should be disabled. Feedback gating restricts submission of feedback (reporting a World or User) to people with the `system_feedback_access` Tag.
    type: boolean
  disableFrontendBuilds:
    default: false
    description: 'Unknown, probably toggles compilation of frontend web builds? So internal flag?'
    type: boolean
  disableHello:
    default: false
    description: Unknown
    type: boolean
  disableOculusSubs:
    default: false
    description: Toggles if signing up for Subscriptions in Oculus is disabled or not.
    type: boolean
  disableRegistration:
    default: false
    description: Toggles if new user account registration should be disabled.
    type: boolean
  disableSteamNetworking:
    default: true
    description: Toggles if Steam Networking should be disabled. VRChat these days uses Photon Unity Networking (PUN) instead.
    type: boolean
  disableTwoFactorAuth:
    default: false
    deprecated: true
    description: Toggles if 2FA should be disabled.
    type: boolean
  disableUdon:
    default: false
    description: Toggles if Udon should be universally disabled in-game.
    type: boolean
  disableUpgradeAccount:
    default: false
    description: Toggles if account upgrading "linking with Steam/Oculus" should be disabled.
    type: boolean
  downloadLinkWindows:
    description: Download link for game on the Oculus Rift website.
    minLength: 1
    type: string
  downloadUrls:
    $ref: ./APIConfigDownloadURLList.yaml
  dynamicWorldRows:
    description: 'Array of DynamicWorldRow objects, used by the game to display the list of world rows'
    minItems: 1
    type: array
    uniqueItems: true
    items:
      $ref: ./DynamicContentRow.yaml
  events:
    $ref: ./APIConfigEvents.yaml
  gearDemoRoomId:
    deprecated: true
    description: Unknown
    minLength: 1
    type: string
  homeWorldId:
    $ref: ./WorldID.yaml
  homepageRedirectTarget:
    default: 'https://hello.vrchat.com'
    description: Redirect target if you try to open the base API domain in your browser
    minLength: 1
    type: string
  hubWorldId:
    $ref: ./WorldID.yaml
  jobsEmail:
    description: VRChat's job application email
    minLength: 1
    type: string
  messageOfTheDay:
    deprecated: true
    description: MOTD
    minLength: 1
    type: string
  moderationEmail:
    description: VRChat's moderation related email
    minLength: 1
    type: string
  moderationQueryPeriod:
    description: Unknown
    type: integer
  notAllowedToSelectAvatarInPrivateWorldMessage:
    description: Used in-game to notify a user they aren't allowed to select avatars in private worlds
    minLength: 1
    type: string
  plugin:
    description: 'Extra [plugin](https://doc.photonengine.com/en-us/server/current/plugins/manual) to run in each instance'
    minLength: 1
    type: string
  releaseAppVersionStandalone:
    deprecated: true
    description: Version number for game release build
    minLength: 1
    type: string
  releaseSdkUrl:
    deprecated: true
    description: Link to download the release SDK
    minLength: 1
    type: string
  releaseSdkVersion:
    deprecated: true
    description: Version of the release SDK
    minLength: 1
    type: string
  releaseServerVersionStandalone:
    deprecated: true
    description: Version number for server release build
    minLength: 1
    type: string
  sdkDeveloperFaqUrl:
    description: Link to the developer FAQ
    minLength: 1
    type: string
  sdkDiscordUrl:
    description: Link to the official VRChat Discord
    minLength: 1
    type: string
  sdkNotAllowedToPublishMessage:
    description: Used in the SDK to notify a user they aren't allowed to upload avatars/worlds yet
    minLength: 1
    type: string
  sdkUnityVersion:
    description: Unity version supported by the SDK
    minLength: 1
    type: string
  serverName:
    description: Server name of the API server currently responding
    minLength: 1
    type: string
  supportEmail:
    description: VRChat's support email
    minLength: 1
    type: string
  timeOutWorldId:
    $ref: ./WorldID.yaml
  tutorialWorldId:
    $ref: ./WorldID.yaml
  updateRateMsMaximum:
    description: Unknown
    type: integer
  updateRateMsMinimum:
    description: Unknown
    type: integer
  updateRateMsNormal:
    description: Unknown
    type: integer
  updateRateMsUdonManual:
    description: Unknown
    type: integer
  uploadAnalysisPercent:
    description: Unknown
    type: integer
  urlList:
    description: List of allowed URLs that bypass the "Allow untrusted URL's" setting in-game
    type: array
    items:
      type: string
  useReliableUdpForVoice:
    default: false
    description: Unknown
    type: boolean
  userUpdatePeriod:
    description: Unknown
    type: integer
  userVerificationDelay:
    description: Unknown
    type: integer
  userVerificationRetry:
    description: Unknown
    type: integer
  userVerificationTimeout:
    description: Unknown
    type: integer
  viveWindowsUrl:
    description: Download link for game on the Steam website.
    minLength: 1
    type: string
  whiteListedAssetUrls:
    description: List of allowed URLs that are allowed to host avatar assets
    type: array
    items:
      type: string
  worldUpdatePeriod:
    description: Unknown
    type: integer
  player-url-resolver-hash:
    description: Currently used youtube-dl.exe hash in SHA-256-delimited format
    minLength: 1
    type: string
  player-url-resolver-version:
    description: Currently used youtube-dl.exe version
    minLength: 1
    type: string
required:
  - VoiceEnableDegradation
  - VoiceEnableReceiverLimiting
  - address
  - announcements
  - appName
  - buildVersionTag
  - clientApiKey
  - clientBPSCeiling
  - clientDisconnectTimeout
  - clientReservedPlayerBPS
  - clientSentCountAllowance
  - contactEmail
  - copyrightEmail
  - currentTOSVersion
  - defaultAvatar
  - deploymentGroup
  - devAppVersionStandalone
  - devDownloadLinkWindows
  - devSdkUrl
  - devSdkVersion
  - devServerVersionStandalone
  - dis-countdown
  - disableAvatarCopying
  - disableAvatarGating
  - disableCommunityLabs
  - disableCommunityLabsPromotion
  - disableEmail
  - disableEventStream
  - disableFeedbackGating
  - disableFrontendBuilds
  - disableHello
  - disableOculusSubs
  - disableRegistration
  - disableSteamNetworking
  - disableTwoFactorAuth
  - disableUdon
  - disableUpgradeAccount
  - downloadLinkWindows
  - downloadUrls
  - dynamicWorldRows
  - events
  - gearDemoRoomId
  - homeWorldId
  - homepageRedirectTarget
  - hubWorldId
  - jobsEmail
  - messageOfTheDay
  - moderationEmail
  - moderationQueryPeriod
  - notAllowedToSelectAvatarInPrivateWorldMessage
  - plugin
  - releaseAppVersionStandalone
  - releaseSdkUrl
  - releaseSdkVersion
  - releaseServerVersionStandalone
  - sdkDeveloperFaqUrl
  - sdkDiscordUrl
  - sdkNotAllowedToPublishMessage
  - sdkUnityVersion
  - serverName
  - supportEmail
  - timeOutWorldId
  - tutorialWorldId
  - updateRateMsMaximum
  - updateRateMsMinimum
  - updateRateMsNormal
  - updateRateMsUdonManual
  - uploadAnalysisPercent
  - urlList
  - useReliableUdpForVoice
  - userUpdatePeriod
  - userVerificationDelay
  - userVerificationRetry
  - userVerificationTimeout
  - viveWindowsUrl
  - whiteListedAssetUrls
  - worldUpdatePeriod
  - player-url-resolver-hash
  - player-url-resolver-version
