title: APIConfigLoadingScreenWeights
type: object
properties:
  announcement:
    type: integer
    example: 1
  informational:
    type: integer
    example: 89
  promotional:
    type: integer
    example: 10
