title: APIConfigLoadingScreenWeights
type: object
properties:
  announcement:
    type: integer
    examples:
      - 1
  informational:
    type: integer
    examples:
      - 89
  promotional:
    type: integer
    examples:
      - 10
