title: GroupRoleTemplateValues
type: object
properties:
  basePermissions:
    type: array
    items:
      $ref: ./GroupPermissions.yaml
  description:
    type: string
  name:
    type: string
  roles:
    type: array
    items:
      $ref: ./GroupRoleTemplateRole.yaml
required:
  - basePermissions
  - description
  - name
  - roles
