title: Listing
type: object
properties:
  active:
    type: boolean
  buyerRefundable:
    type: boolean
  description:
    type: string
  displayName:
    type: string
  duration:
    type:
      - integer
      - null
  durationType:
    type:
      - string
      - null
  groupIcon:
    $ref: ./FileID.yaml
    nullable: true
  groupId:
    $ref: ./GroupID.yaml
  groupName:
    type:
      - string
      - null
  hasAvatar:
    type: boolean
  hasUdon:
    type: boolean
  hydratedProducts:
    type: array
    items:
      $ref: ./Product.yaml
  id:
    $ref: ./ProductID.yaml
  imageId:
    $ref: ./FileID.yaml
    nullable: true
  imageUrl:
    type:
      - string
      - null
  listingType:
    $ref: ./ProductListingType.yaml
  listingVariants:
    type: array
    items:
      $ref: ./ProductListingVariant.yaml
  permanent:
    type: boolean
  priceTokens:
    type: integer
  productIds:
    type: array
    items:
      $ref: ./ProductID.yaml
  productType:
    $ref: ./ProductType.yaml
  products:
    type: array
    items:
      type: object
      description: Either a ProductID or a Product, depending on hydration
  quantifiable:
    type: boolean
  recurrable:
    type: boolean
  refundable:
    type: boolean
  sellerDisplayName:
    type: string
  sellerId:
    type: string
  stackable:
    type: boolean
  storeIds:
    type: array
    items:
      type: string
  tags:
    type: array
    items:
      $ref: ./Tag.yaml
required:
  - active
  - buyerRefundable
  - description
  - displayName
  - hasAvatar
  - hasUdon
  - id
  - listingType
  - priceTokens
  - productIds
  - productType
  - products
  - recurrable
  - refundable
  - sellerDisplayName
  - sellerId
  - stackable
  - storeIds
