title: Listing
type: object
properties:
  active:
    type: boolean
  archived:
    type: boolean
  attribution:
    $ref: ./ProductListingAttribution.yaml
  buyerRefundable:
    type: boolean
  collabUserDisplayName:
    type: ["null", string]
  collabUserId:
    $ref: ./UserID.yaml
  created:
    type: string
    format: date-time
  description:
    type: string
  displayName:
    type: string
  duration:
    type: [integer, "null"]
  durationType:
    type: ["null", string]
  groupIcon:
    type: [./FileID.yaml, "null"]
  groupId:
    $ref: ./GroupID.yaml
  groupName:
    type: ["null", string]
  hasAvatar:
    type: boolean
  hasCompanion:
    type: boolean
  hasInventory:
    type: boolean
  hasUdon:
    type: boolean
  hydratedProducts:
    type: array
    items:
      $ref: ./Product.yaml
  id:
    $ref: ./ProductID.yaml
  imageId:
    type: [./FileID.yaml, "null"]
  imageUrl:
    type: ["null", string]
  listingType:
    $ref: ./ProductListingType.yaml
  listingVariants:
    type: array
    items:
      $ref: ./ProductListingVariant.yaml
  permanent:
    type: boolean
  priceTokens:
    type: integer
  productIds:
    type: array
    items:
      $ref: ./ProductID.yaml
  productType:
    $ref: ./ProductType.yaml
  productTypes:
    type: array
    items:
      type: string
  products:
    type: array
    description: Product ids. The products themselves arrive in `hydratedProducts`.
    items:
      $ref: ./ProductID.yaml
  purchaseCount:
    type: integer
  purchaseCountQuantity:
    type: integer
  quantifiable:
    type: boolean
  recurrable:
    type: boolean
  refundable:
    type: boolean
  sellerDisplayName:
    type: string
  sellerId:
    type: string
  soldByVrc:
    type: boolean
  stackable:
    type: boolean
  storeIds:
    type: array
    items:
      $ref: ./StoreID.yaml
  subtitle:
    type: string
  tags:
    type: array
    items:
      $ref: ./Tag.yaml
  updated:
    type: string
    format: date-time
  vrcPlusDiscountPrice:
    type: integer
  whenToExpire:
    type: ["null", string]
    format: date-time
required:
  - active
  - buyerRefundable
  - description
  - displayName
  - hasAvatar
  - hasUdon
  - id
  - listingType
  - priceTokens
  - productIds
  - productType
  - products
  - recurrable
  - sellerDisplayName
  - sellerId
  - stackable
