title: ProductListingVariant
type: object
properties:
  effectiveFrom:
    type: string
    format: date-time
  listingVariantId:
    anyOf:
      - $ref: ./ProductListingVariantID.yaml
      - type: "null"
  nonRefundable:
    type: boolean
  quantity:
    type: integer
  sellerVariant:
    type: boolean
  unitPriceTokens:
    type: integer
required:
  - listingVariantId
  - nonRefundable
  - quantity
  - sellerVariant
  - unitPriceTokens
