title: ProductPurchaseProduct
type: object
properties:
  displayName:
    type: string
  id:
    $ref: ./ProductID.yaml
  imageId:
    type: [./FileID.yaml, "null"]
  licenseId:
    type: ["null", string]
  productType:
    $ref: ./ProductType.yaml
required:
  - displayName
  - id
  - productType
