title: ProductPurchaseProduct
type: object
properties:
  displayName:
    type: string
  id:
    $ref: ./ProductID.yaml
  imageId:
    $ref: ./FileID.yaml
    nullable: true
  licenseId:
    type: string
    nullable: true
  productType:
    $ref: ./ProductType.yaml
required:
  - displayName
  - id
  - productType
