title: ProductPurchaseRecord
type: object
properties:
  amount:
    type: integer
    examples:
      - 399
  balance:
    type: integer
    examples:
      - 399
  date:
    type: string
    format: date-time
  fromUserDisplayName:
    type: string
    examples:
      - VRChat
  listingDisplayName:
    type: string
    examples:
      - Lucky Red Envelope
  listingType:
    $ref: ./ProductListingType.yaml
  platform:
    type: string
    description: Where (first- or third-party) the purchase was made
    examples:
      - VRChat
  purchaseId:
    $ref: ./ProductPurchaseID.yaml
  reason:
    type: integer
    examples:
      - 3002
  reasonLabel:
    type: string
    examples:
      - Promo Credit
  transactionId:
    type: integer
  transactionLineId:
    type: integer
required:
  - amount
  - balance
  - date
  - fromUserDisplayName
  - listingDisplayName
  - listingType
  - platform
  - purchaseId
  - reason
  - reasonLabel
  - transactionId
  - transactionLineId
