title: ProductPurchaseProduct
type: object
properties:
  displayName:
    type: string
  id:
    $ref: ./ProductID.yaml
  imageId:
    anyOf:
      - $ref: ./FileID.yaml
      - type: "null"
  licenseId:
    type: ["null", string]
  productType:
    $ref: ./ProductType.yaml
required:
  - displayName
  - id
  - productType
