number:
  name: 'n'
  in: query
  required: false
  schema:
    type: integer
    maximum: 100
    minimum: 1
    default: 60
  description: The number of objects to return.
offset:
  name: offset
  in: query
  required: false
  schema:
    type: integer
    minimum: 0
  description: A zero-based offset from the default object sorting from where search results start.
sort:
  name: sort
  in: query
  required: false
  schema:
    $ref: ./schemas/SortOption.yaml
  description: The sort order of the results.
order:
  name: order
  in: query
  required: false
  schema:
    $ref: ./schemas/OrderOption.yaml
  description: Result ordering
releaseStatus:
  name: releaseStatus
  in: query
  required: false
  schema:
    $ref: ./schemas/ReleaseStatus.yaml
  description: Filter by ReleaseStatus.
offline:
  name: offline
  in: query
  required: false
  schema:
    type: boolean
  description: 'Returns *only* offline users if true, returns only online and active users if false'
fileId:
  name: fileId
  in: path
  required: true
  schema:
    type: string
    example: file_00000000-0000-0000-0000-000000000000
    pattern: 'file_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'
  description: Must be a valid file ID.
groupId:
  name: groupId
  in: path
  required: true
  schema:
    type: string
    example: grp_00000000-0000-0000-0000-000000000000
    pattern: 'grp_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'
  description: Must be a valid group ID.
groupRoleId:
  name: groupRoleId
  in: path
  required: true
  schema:
    type: string
    example: grol_00000000-0000-0000-0000-000000000000
    pattern: 'grol_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'
versionId:
  name: versionId
  in: path
  required: true
  schema:
    type: integer
    minimum: 1
    example: 1
  description: Version ID of the asset.
fileType:
  name: fileType
  in: path
  required: true
  schema:
    type: string
    enum:
      - file
      - signature
      - delta
    example: file
  description: Type of file.
userId:
  name: userId
  in: path
  required: true
  schema:
    type: string
  description: Must be a valid user ID.
userIdQuery:
  name: userId
  in: query
  required: false
  schema:
    type: string
  description: Filter by UserID.
excludeUserId:
  name: excludeUserId
  in: query
  required: false
  schema:
    type: string
  description: Exclude by UserID.
displayName:
  name: displayName
  in: query
  required: false
  schema:
    type: string
  description: Filter by displayName.
email:
  name: email
  in: query
  required: false
  schema:
    type: string
  description: Filter by email.
maxUnityVersion:
  name: maxUnityVersion
  in: query
  required: false
  schema:
    type: string
  description: The maximum Unity version supported by the asset.
minUnityVersion:
  name: minUnityVersion
  in: query
  required: false
  schema:
    type: string
  description: The minimum Unity version supported by the asset.
platform:
  name: platform
  in: query
  required: false
  schema:
    type: string
  description: The platform the asset supports.
tag:
  name: tag
  in: query
  required: false
  schema:
    type: string
  description: Tags to include (comma-separated). Any of the tags needs to be present.
include:
  name: include
  in: query
  required: false
  schema:
    type: string
  description: Tags to include (comma-separated). Any of the tags needs to be present.
require:
  name: require
  in: query
  required: false
  schema:
    type: string
  description: Tags to include (comma-separated). All of the tags needs to be present.
notag:
  name: notag
  in: query
  required: false
  schema:
    type: string
  description: Tags to exclude (comma-separated).
search:
  name: search
  in: query
  required: false
  schema:
    type: string
  description: Filters by world name.
featured:
  name: featured
  in: query
  required: false
  schema:
    type: boolean
  description: Filters on featured results.
userIdAdmin:
  name: userId
  in: query
  required: false
  schema:
    type: string
  description: 'Target user to see information on, admin-only.'
worldId:
  name: worldId
  in: path
  required: true
  schema:
    type: string
  description: Must be a valid world ID.
instanceId:
  name: instanceId
  in: path
  required: true
  schema:
    type: string
favoriteId:
  name: favoriteId
  in: path
  required: true
  schema:
    type: string
favoriteGroupType:
  name: favoriteGroupType
  in: path
  required: true
  schema:
    type: string
    enum:
      - world
      - friend
      - avatar
  description: 'The type of group to fetch, must be a valid FavoriteType.'
favoriteGroupName:
  name: favoriteGroupName
  in: path
  required: true
  schema:
    type: string
avatarId:
  name: avatarId
  in: path
  required: true
  schema:
    type: string
messageType:
  name: messageType
  in: path
  required: true
  schema:
    type: string
    enum:
      - message
      - response
      - request
      - requestResponse
slot:
  name: slot
  in: path
  required: true
  schema:
    type: integer
    minimum: 0
    maximum: 11
notificationId:
  name: notificationId
  in: path
  required: true
  schema:
    type: string
permissionId:
  name: permissionId
  in: path
  required: true
  schema:
    type: string
transactionId:
  name: transactionId
  in: path
  required: true
  schema:
    type: string
licenseGroupId:
  name: licenseGroupId
  in: path
  required: true
  schema:
    type: string
variant:
  name: variant
  in: query
  required: false
  schema:
    type: string
    enum:
      - public
      - internal
    default: public
  allowEmptyValue: true
  description: 'Specifies which `variant` of the site. Public is the end-user site, while `internal` is the staff-only site with special pages for moderation and management.'
branch:
  name: branch
  in: query
  required: false
  schema:
    type: string
    default: main
  allowEmptyValue: true
  description: Specifies which git branch the site should load frontend source code from.