on:
  workflow_call:
    inputs:
      language:
        description: The client to build.
        required: true
        type: string

jobs:
  javascript:
    if: inputs.language == 'javascript'
    uses: vrchatapi/vrchatapi-javascript/.github/workflows/ci.yaml@main

  rust:
    if: inputs.language == 'rust'
    uses: vrchatapi/vrchatapi-rust/.github/workflows/ci.yaml@main

  java:
    if: inputs.language == 'java'
    uses: vrchatapi/vrchatapi-java/.github/workflows/ci.yaml@main

  python:
    if: inputs.language == 'python'
    uses: vrchatapi/vrchatapi-python/.github/workflows/ci.yaml@main

  csharp:
    if: inputs.language == 'csharp'
    uses: vrchatapi/vrchatapi-csharp/.github/workflows/ci.yaml@main

  dart:
    if: inputs.language == 'dart'
    uses: vrchatapi/vrchatapi-dart/.github/workflows/ci.yaml@main
