on: [push, pull_request]
name: Continuous Integration

jobs:
  bundle:
    runs-on: ubuntu-latest
    name: Bundle OpenAPI specification
    steps:
      - uses: actions/checkout@v2

      - name: OpenAPI CLI Bundle
        uses: hilary/openapi-cli-bundle-action@v0.0.2
        with:
          base-spec: openapi.yaml
          bundled-spec: dist/openapi-bundled.yml
          
      - name: Store bundled specification
        uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: dist/openapi-bundled.yml