on: [push, pull_request]
name: Continuous Integration

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint OpenAPI specification
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v12
      - name: Install Dependencies
        run: npm install
      - name: Run Spectral linting
        run: npm run lint

  bundle:
    runs-on: ubuntu-latest
    name: Bundle OpenAPI specification
    steps:
      - uses: actions/checkout@v2

      - name: OpenAPI CLI Bundle
        uses: hilary/openapi-cli-bundle-action@v0.0.2
        with:
          base-spec: openapi.yaml
          bundled-spec: dist/openapi-bundled.yml
          
      - name: Store bundled specification
        uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: dist/openapi-bundled.yml