on: [push, pull_request]

name: OpenAPI Specification CI

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint OpenAPI specification
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v14
      - name: Install Dependencies
        run: npm install
      - name: Run Spectral linting
        run: npm run lint

  bundle:
    needs: lint
    runs-on: ubuntu-latest
    name: Bundle and Filter OpenAPI specification
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v14

      - name: Bundle OpenAPI Specification 📦
        run: npm run bundle

      - name: Upload Bundled Specification as Artifact 📤
        uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: dist

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: bundle
    runs-on: ubuntu-latest
    name: Release Bundle as new Version
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: openapi-bundled
        path: dist

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/openapi.yaml"
        artifactErrorsFailBuild: true
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}

  pages:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: bundle
    runs-on: ubuntu-latest
    name: Upload OpenAPI specification to GitHub Pages
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: openapi-bundled
          path: dist

      - name: Disable Jekyll for Github Pages
        run: sudo touch dist/.nojekyll; sudo touch dist/index.html

      - name: Prevent Cloudflare Pages (used for dev preview) from breaking
        run: mkdir dist/dist; cp dist/openapi.yaml dist/dist/openapi.yaml; cp .github/files/empty.json dist/package.json

      - name: Deploy Bundle to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist

  # https://blog.marcnuri.com/triggering-github-actions-across-different-repositories
  # Make sure this is same as in sdk_generate.yaml
  sdk_generate:
    needs: pages
    runs-on: ubuntu-latest
    name: Trigger Remote SDK builds
    strategy:
      matrix:
        project:
          - javascript
          - csharp
          - python
          - java
          - rust
    steps:
      - name: Triggering build SDK - ${{ matrix.node }}
        run: |
          curl -X POST https://api.github.com/repos/vrchatapi/vrchatapi-${{ matrix.project }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "spec_release"}'